# (PART) Research {-} 

# Teach -- Learn -- Repeat

<!-- Conceptional Background -->
<!-- A Question You Care About -->
<!-- subtitle: "A Kickstart for Social Scientists" -->
<!-- In order to pass a math class, become the head of a study group.  -->
<!-- Humans feel positive emotion when they have social ties. -->

I fell in love with [learning by teaching](https://en.wikipedia.org/wiki/Learning_by_teaching) the moment I came across this concept. It put the experiences I made into scientific context. I had to pass math classes in my undergraduates, and I became a math tutor for years. I really wanted to master ballroom dance, so I became a dance instructor for life. 

The mode of teaching can differ. I started teaching in the classroom and ballroom and have a standing on Wikipedia. You can contribute on Wikipedia and will get feedback on your neutral point of view, academic writing and rigor. Feedback on YouTube and Social Media can be more diffuse. Now, I turn to writing a book from my collected notes (and questions) on empirical research. I hope to force myself to pinpoint exactly what I know and don't know and how to fill the gaps. Luckily, I am not alone with the approach of creating classes or writing books to learn. 

> I could feel that econometrics was indispensable, and yet I was missing something. But what? It was a theory of causality […]. <b>So, desperate, I did what I always do when I want to learn something new — I developed a course on causality to force myself to learn all the things I didn’t know.</b>
>
> `r tufte::quote_footer('Scott Cunningham. In: Causal Inference – The Mixtape')`

This project helped me to learn more about R, RStudio, R Markdown, R Bookdown, HTML/CSS, Git and Github, empirical research, causal inference, statistics, math, frustration tolerance and fun.

<!-- I had the need to learn more about empirical analysis and causal inference. Thus I started a series of seminars covering a mixture of data science, econometrics, statistics and reporting.  -->

<!-- <https://lindeloev.github.io/tests-as-linear/> -->


