
## Install Github and Git

- Get RStudio <https://www.rstudio.com/products/rstudio/download/>
- Get Github account <https://github.com/>
- Set up Github pages <https://pages.github.com/>
- Download Git <https://git-scm.com/>

Create a "special repository" for GitHub Pages. Only this can turn the branch into docs (1 for free).

- Repository: https://github.com/MarcoKuehne/marcokuehne.github.io
- Homepage: https://marcokuehne.github.io/

Create (or re-open) your R project inside RStudio. 

In R console use `usethis::use_git()` which always gives three different answers in random order. Confirm accordingly.

## Working with Git

Use the terminal inside RStudio. Copy paste into terminal with: `CTRL + SHIFT + V`.

### git version

Let's start with commands that cannot do any harm (it's 2.32 in 08/2021): 

    git version

### git config 

First, configure github user information on your system. Use the R builtin terminal:

    git config --global user.email MAIL
    git config --global user.name NAME
    
Now, you can commit (upload) changes from RStudio to Github Pages. Check out `git config --list`.

### git init

Use `git init` to initialize the repository. It is used to create a new empty repository or directory consisting of files' with the hidden directory. '.git' is created at the top level of your project, which places all of the revision information in one place.

Show what is connected with:

    git remote -v show

### git status and diff

Shows you which files are in this staging area, and which files have changes that haven't yet been put there. In order to compare the file as it currently is to what you last saved, you can use `git diff filename`, e.g. `git diff README.md` in the terminal. `git diff` without any file names will show you all the changes in your repository, while git diff directory will show you the changes to the files in some directory.

### git commit 

To save the changes in the staging area, you use the command `git commit`. It always saves everything that is in the staging area as one unit: as you will see later, when you want to undo changes to a project, you undo all of a commit or none of it.

Commit requires a message (comment). How to write a good git commit message:l

<https://chris.beams.io/posts/git-commit/>

### git add

Edit something in the README.md:

    git add README.md
    git commit -m "added something in the readme"
    git push 

How to push? Easy ... 

### git remote add

I would like to have something like `git remote add ...` and `git push ...`, not working.

I can add and remove origins, don't know what it means: `git remote rm origin`

Use git add . in your bash to add all the files to the given folder.

Use git status in your bash to view all the files which are going to be staged to the first commit.

Create **git remote add**

git remote add origin https://github.com/MarcoKuehne/marcokuehne.github.git 
git remote add origin https://github.com/MarcoKuehne/marcokuehne.github.io
git remote add origin https://github.com/MarcoKuehne/marcokuehne.github.io.git

git remote add git@github.com:<username>/<repository-name>.git
git remote add git@github.com:MarcoKuehne/marcokuehne.github.git
git remote add git@github.com:MarcoKuehne/marcokuehne.github.io does not appear to be a repository 
git remote add git@github.com:MarcoKuehne/marcokuehne.github.io.git combine both 

### git push 

git push -u origin main
git push -u origin master
git push origin master
git push origin main 
git push --set-upstream origin main
git push -f origin main # worked somehow!!!

If positive, it asks for github credentials. 

<https://www.datacamp.com/community/tutorials/git-push-pull>


### Basic Routine: Commit + Push 

I make changes to one of my markdown fiels, e.g. the `README.md` (this can also be done via GitHub web interface) on my local machine. After notoriously saving this on my local machine (STRG+S) it appears in the *stage area* in the right upper panel in RStudio. Commit and push can be either done in RStudio or via terminal line (also in RStudio). 

First, let's do it via "clicking". Select the staged file. Click "commit". A new windows opens and displays the changes in your file. Write a new commit message of amend a previous commit. Click "close". From this additional window (or the right upper panel in RStudio) click the green push arrow. Hopefully it will say "HEAD -> main". Close. Done. 



I need to `pull` these changes into RStudio. Check the right upper panel "Diff". Select `pull`. You can also find big blue down and green up arrows. 

I add this sentence. I save on RStudio, thus it appears as a change to `README.md` in the Git panel. I select this file and green up arrow (push). I enter my credentials and close (see <https://docs.github.com/en/get-started/getting-started-with-git/why-is-git-always-asking-for-my-password>). Here you might use a personal access token. I click `commit`, enter a commit message, click `commit` again and close the extra window. 


## Resources

You can start reading about bookdowns from the inventor:

<https://bookdown.org/yihui/bookdown/>

This is pretty advanced and I can't understand a tiny piece of it. 

Another option is to start a repo and book by copying "awesome book" from another repo.

<https://jules32.github.io/bookdown-tutorial/setup.html>

This tutorial worked to push a book to a standard repo. But there were problem with the doc branch.

After I forgot how to start my project or where to find it, I checked:

<https://happygitwithr.com/rstudio-git-github.html#make-local-changes-save-commit>

started a new project with my repo link and a new session. This forks or fetches or pulls or downloads the repo. Now I will try to re-upload the minimal change from today. 

Another personal description can be found here:

<https://rachaellappan.github.io/bookdown/>

    This enourmously helped with the understanding of commits and pushs on git:
    
    <http://www.differencebetween.net/technology/difference-between-commit-and-push/>

- `git commit -m "Started book"`

I followed the video "How to create a bookdown book in 5 minutes":

<https://www.youtube.com/watch?v=m5D-yoH416Y>

It did not work.

Explaining terminology:

<https://www.notion.so/zarkom/Introduction-to-Git-ac396a0697704709a12b6a0e545db049>


Learn Git in 15 Min:

<https://www.youtube.com/watch?v=USjZcfj8yxE>

Learn GitHub in 20 Min:

<https://www.youtube.com/watch?v=nhNq2kIvi9s> 











