# A Question You Care About {-}

<!-- ::: {.infobox .information data-latex="warning"} -->
<!-- The first and most important point is to choose a topic that you really care about.  -->
<!-- ::: -->

Are you passionate about something? Research starts off from a question you really care about. Math, statistics and programming are easier to digest when you are intrinsically motivated to find out more about your topic of interest. This is a brief guide on the main parts of the empirical research process. There's more to the end of it. After answering the research question, a theoretical interpretation can be derived, results are compared to earlier research and conclusions are drawn. 

Give it a personal touch if possible. The topic can be related to hobbies, family or friends, education, job or neighborhood. It can be something from the present or past. It can be a pet as well as personality, believes and attitudes. It can be gardening or Fortnite. Choose something that you are really interested in. Next, retain a neutral point of view. Collect and analyze data first, discuss and compare your results to others, conclude at the end. 

<!-- Statistics anxiety Onwuegbuzie, A. J., & Wilson, V. A. (2003). Statistics Anxiety: Nature, etiology, antecedents, effects, and treatments--a comprehensive review of the literature. Teaching in higher education, 8(2), 195-209. -->

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(DiagrammeR)

grViz(diagram = "digraph flowchart {
  node [fontname = arial, shape = oval, color = grey, style = filled]
  tab1 [label = '@@1']
  tab2 [label = '@@2']
  tab3 [label = '@@3']
  tab4 [label = '@@4']
  tab5 [label = '@@5']
  
  tab1 -> tab2 -> tab3 -> tab4 -> tab5 -> tab1;
}
  
  [1]: 'Research Idea'
  [2]: 'Literature Review'
  [3]: 'Empirical Research Question'    
  [4]: 'Data Collection'    
  [5]: 'Data Analysis'    
  ")
```

::: {.infobox .information data-latex="warning"}
<details>
<summary>What you can learn ... </summary>
- What is at the heart of empirical research: Questions. 
- How to get and handle tabular data. 
- The principles of relationships and trends.
- How to model relationships with equations. 
- Estimate a relationship with Regression. 
- The implementation in the statistical software R.
</details>
:::

<!-- how to do it yourself instead of relying on data and analysis from someone else. -->

<!-- The chances are pretty high that there is data on your subject.  -->

<!-- A good research question is essential to guide your research paper or thesis. It pinpoints exactly what you want to find out and gives your work a clear focus and purpose. All research questions should be focused, specific and relevant. An empirical research question can be answered by collecting and analyzing data. -->

<!-- ```{r letter-a, echo=FALSE} -->
<!-- library(learnr) -->
<!-- question("What number is the letter A in the English alphabet?", -->
<!--  answer("8"), -->
<!--  answer("14"), -->
<!--  answer("1", correct = TRUE), -->
<!--  answer("23") -->
<!-- ) -->
<!-- ``` -->



