<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Relationships | Becoming Fluent in Data</title>
  <meta name="description" content="A guide to become fluent in data." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Relationships | Becoming Fluent in Data" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/Cover.png" />
  <meta property="og:description" content="A guide to become fluent in data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Relationships | Becoming Fluent in Data" />
  
  <meta name="twitter:description" content="A guide to become fluent in data." />
  <meta name="twitter:image" content="/images/Cover.png" />

<meta name="author" content="Marco Kühne" />


<meta name="date" content="2024-02-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/Logo.ico" type="image/x-icon" />
<link rel="prev" href="missing-data.html"/>
<link rel="next" href="regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.31/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/tippyjs-3.2.0/themes/google.css" rel="stylesheet" />
<link href="libs/tippyjs-3.2.0/themes/light-border.css" rel="stylesheet" />
<link href="libs/tippyjs-3.2.0/themes/light.css" rel="stylesheet" />
<link href="libs/tippyjs-3.2.0/themes/translucent.css" rel="stylesheet" />
<script src="libs/tippyjs-3.2.0/tippy.all.min.js"></script>
<script src="libs/tippy-binding-0.1.0/tippy.js"></script>
<script type="application/json" class="js-hypothesis-config">
{
"showHighlights": false
}
</script>
<script async defer src="https://hypothes.is/embed.js"></script>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P9BQG7T00K"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P9BQG7T00K');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="www/webex.css" type="text/css" />
<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/box_def.css" type="text/css" />
<link rel="stylesheet" href="css/box_amazing.css" type="text/css" />
<link rel="stylesheet" href="css/box_challenge.css" type="text/css" />
<link rel="stylesheet" href="css/box_dedicated.css" type="text/css" />
<link rel="stylesheet" href="css/box_reading.css" type="text/css" />
<link rel="stylesheet" href="css/ani.css" type="text/css" />
<link rel="stylesheet" href="css/background.css" type="text/css" />
<link rel="stylesheet" href="css/toggle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://marcokuehne.github.io/">Becoming Fluent in Data</a></li> <li><p class="aligncenter"> <img src="images/Logo.png" width="60%" height="60%"> </p></li>
<li class="divider"></li>
<li class="part"><span><b>I Intro</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aims-of-this-book"><i class="fa fa-check"></i>Aims of this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-students"><i class="fa fa-check"></i>For students</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-instructors"><i class="fa fa-check"></i>For instructors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure"><i class="fa fa-check"></i>Structure</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#color"><i class="fa fa-check"></i>Color</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#components"><i class="fa fa-check"></i>Components</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i>Why R?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-tidyverse"><i class="fa fa-check"></i>Why Tidyverse?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dust-and-dark"><i class="fa fa-check"></i>Dust and Dark</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teach-learn-repeat"><i class="fa fa-check"></i>Teach – Learn – Repeat</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html"><i class="fa fa-check"></i>Intro to R</a>
<ul>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#r-is-a-calculator"><i class="fa fa-check"></i>R is a calculator</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#r-is-more-than-a-calculator"><i class="fa fa-check"></i>R is more than a calculator</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#define-objects"><i class="fa fa-check"></i>Define objects</a>
<ul>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#numeric-variables"><i class="fa fa-check"></i>Numeric Variables</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#logical-variables"><i class="fa fa-check"></i>Logical Variables</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#string-variables"><i class="fa fa-check"></i>String Variables</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#factor-variables"><i class="fa fa-check"></i>Factor Variables</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#combine-objects"><i class="fa fa-check"></i>Combine objects</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#vectors"><i class="fa fa-check"></i>Vectors</a></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#data-frame"><i class="fa fa-check"></i>Data frame</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intro-to-r.html"><a href="intro-to-r.html#plots"><i class="fa fa-check"></i>Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html"><i class="fa fa-check"></i>Intro to Tidyverse</a>
<ul>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#data-with-readr"><i class="fa fa-check"></i>Data with readr</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#verbs-of-dplyr"><i class="fa fa-check"></i>Verbs of dplyr</a>
<ul>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#glimpse"><i class="fa fa-check"></i>Glimpse</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#select"><i class="fa fa-check"></i>Select</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#arrange"><i class="fa fa-check"></i>Arrange</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#rename"><i class="fa fa-check"></i>Rename</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#the-pipe-operator"><i class="fa fa-check"></i>The pipe operator</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#filter"><i class="fa fa-check"></i>Filter</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#mutate"><i class="fa fa-check"></i>Mutate</a></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intro-to-tidyverse.html"><a href="intro-to-tidyverse.html#graphs-with-ggplot2"><i class="fa fa-check"></i>Graphs with ggplot2</a></li>
</ul></li>
<li class="part"><span><b>II Data</b></span></li>
<li class="chapter" data-level="1" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html"><i class="fa fa-check"></i><b>1</b> Data is everywhere</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#why-we-measure"><i class="fa fa-check"></i><b>1.1</b> Why we measure</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#women-are-having-far-fewer-children."><i class="fa fa-check"></i><b>1.1.1</b> Women are having far fewer children.</a></li>
<li class="chapter" data-level="1.1.2" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#global-surface-temperature-is-rising."><i class="fa fa-check"></i><b>1.1.2</b> Global surface temperature is rising.</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#means-of-measuring"><i class="fa fa-check"></i><b>1.2</b> Means of measuring</a></li>
<li class="chapter" data-level="1.3" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#types-of-data"><i class="fa fa-check"></i><b>1.3</b> Types of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#origin-of-data"><i class="fa fa-check"></i><b>1.3.1</b> Origin of data</a></li>
<li class="chapter" data-level="1.3.2" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#analysis-of-data"><i class="fa fa-check"></i><b>1.3.2</b> Analysis of data</a></li>
<li class="chapter" data-level="1.3.3" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#structure-of-data"><i class="fa fa-check"></i><b>1.3.3</b> Structure of data</a></li>
<li class="chapter" data-level="1.3.4" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#the-level-of-access"><i class="fa fa-check"></i><b>1.3.4</b> The level of access</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#can-we-measure-everything"><i class="fa fa-check"></i><b>1.4</b> Can we measure everything?</a></li>
<li class="chapter" data-level="1.5" data-path="data-is-everywhere.html"><a href="data-is-everywhere.html#the-reality-behind-the-data"><i class="fa fa-check"></i><b>1.5</b> The reality behind the data</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html"><i class="fa fa-check"></i><b>2</b> Stories and Visuals</a>
<ul>
<li class="chapter" data-level="2.1" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#facts"><i class="fa fa-check"></i><b>2.1</b> Facts</a></li>
<li class="chapter" data-level="2.2" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#visualization"><i class="fa fa-check"></i><b>2.2</b> Visualization</a></li>
<li class="chapter" data-level="2.3" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#telling-a-story"><i class="fa fa-check"></i><b>2.3</b> Telling a story</a></li>
<li class="chapter" data-level="2.4" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#mans-best-friend"><i class="fa fa-check"></i><b>2.4</b> Man's best friend</a></li>
<li class="chapter" data-level="2.5" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#less-is-more"><i class="fa fa-check"></i><b>2.5</b> Less is more</a></li>
<li class="chapter" data-level="2.6" data-path="stories-and-visuals.html"><a href="stories-and-visuals.html#grammar-of-graphics"><i class="fa fa-check"></i><b>2.6</b> Grammar of Graphics</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tabular-data.html"><a href="tabular-data.html"><i class="fa fa-check"></i><b>3</b> Tabular Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tabular-data.html"><a href="tabular-data.html#types-of-tabular-data"><i class="fa fa-check"></i><b>3.1</b> Types of Tabular Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="tabular-data.html"><a href="tabular-data.html#cross-section"><i class="fa fa-check"></i><b>3.1.1</b> Cross-section</a></li>
<li class="chapter" data-level="3.1.2" data-path="tabular-data.html"><a href="tabular-data.html#repeated-cross-section"><i class="fa fa-check"></i><b>3.1.2</b> Repeated cross-section</a></li>
<li class="chapter" data-level="3.1.3" data-path="tabular-data.html"><a href="tabular-data.html#time-series"><i class="fa fa-check"></i><b>3.1.3</b> Time series</a></li>
<li class="chapter" data-level="3.1.4" data-path="tabular-data.html"><a href="tabular-data.html#panel-data"><i class="fa fa-check"></i><b>3.1.4</b> Panel data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="panel-data-1.html"><a href="panel-data-1.html"><i class="fa fa-check"></i><b>4</b> Panel Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="panel-data-1.html"><a href="panel-data-1.html#unemployment"><i class="fa fa-check"></i><b>4.1</b> Unemployment</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="panel-data-1.html"><a href="panel-data-1.html#on-decline-in-germany"><i class="fa fa-check"></i><b>4.1.1</b> On decline in Germany</a></li>
<li class="chapter" data-level="4.1.2" data-path="panel-data-1.html"><a href="panel-data-1.html#measurement"><i class="fa fa-check"></i><b>4.1.2</b> Measurement</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="panel-data-1.html"><a href="panel-data-1.html#application"><i class="fa fa-check"></i><b>4.2</b> Application</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="panel-data-1.html"><a href="panel-data-1.html#data-inspection"><i class="fa fa-check"></i><b>4.2.1</b> Data Inspection</a></li>
<li class="chapter" data-level="4.2.2" data-path="panel-data-1.html"><a href="panel-data-1.html#data-preparation"><i class="fa fa-check"></i><b>4.2.2</b> Data Preparation</a></li>
<li class="chapter" data-level="4.2.3" data-path="panel-data-1.html"><a href="panel-data-1.html#data-visualization"><i class="fa fa-check"></i><b>4.2.3</b> Data Visualization</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="panel-data-1.html"><a href="panel-data-1.html#panel-studies"><i class="fa fa-check"></i><b>4.3</b> Panel Studies</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="time-data.html"><a href="time-data.html"><i class="fa fa-check"></i><b>5</b> Time data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="time-data.html"><a href="time-data.html#measuring-time"><i class="fa fa-check"></i><b>5.1</b> Measuring Time</a></li>
<li class="chapter" data-level="5.2" data-path="time-data.html"><a href="time-data.html#measuring-dates"><i class="fa fa-check"></i><b>5.2</b> Measuring Dates</a></li>
<li class="chapter" data-level="5.3" data-path="time-data.html"><a href="time-data.html#your-first-time-in-r"><i class="fa fa-check"></i><b>5.3</b> Your First Time (in R)</a></li>
<li class="chapter" data-level="5.4" data-path="time-data.html"><a href="time-data.html#time-zones"><i class="fa fa-check"></i><b>5.4</b> Time Zones</a></li>
<li class="chapter" data-level="5.5" data-path="time-data.html"><a href="time-data.html#time-management-in-r"><i class="fa fa-check"></i><b>5.5</b> Time Management in R</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="time-data.html"><a href="time-data.html#decimal-time"><i class="fa fa-check"></i><b>5.5.1</b> Decimal Time</a></li>
<li class="chapter" data-level="5.5.2" data-path="time-data.html"><a href="time-data.html#time-formats"><i class="fa fa-check"></i><b>5.5.2</b> Time Formats</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="time-data.html"><a href="time-data.html#coffee-spending"><i class="fa fa-check"></i><b>5.6</b> Coffee Spending</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="time-data.html"><a href="time-data.html#spending-time-of-day"><i class="fa fa-check"></i><b>5.6.1</b> Spending Time of Day</a></li>
<li class="chapter" data-level="5.6.2" data-path="time-data.html"><a href="time-data.html#run-chart"><i class="fa fa-check"></i><b>5.6.2</b> Run Chart</a></li>
<li class="chapter" data-level="5.6.3" data-path="time-data.html"><a href="time-data.html#run-chart-grouped"><i class="fa fa-check"></i><b>5.6.3</b> Run Chart Grouped</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="time-data.html"><a href="time-data.html#run-chart-grouped-cleaned"><i class="fa fa-check"></i><b>5.7</b> Run Chart Grouped Cleaned</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="web-data.html"><a href="web-data.html"><i class="fa fa-check"></i><b>6</b> Web Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="web-data.html"><a href="web-data.html#most-expensive-paintings"><i class="fa fa-check"></i><b>6.1</b> Most expensive paintings</a></li>
<li class="chapter" data-level="6.2" data-path="web-data.html"><a href="web-data.html#student-numbers-at-viadrina"><i class="fa fa-check"></i><b>6.2</b> Student numbers at Viadrina</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="web-data.html"><a href="web-data.html#pdf-scraping"><i class="fa fa-check"></i><b>6.2.1</b> PDF scraping</a></li>
<li class="chapter" data-level="6.2.2" data-path="web-data.html"><a href="web-data.html#share-of-female-students"><i class="fa fa-check"></i><b>6.2.2</b> Share of female students</a></li>
<li class="chapter" data-level="6.2.3" data-path="web-data.html"><a href="web-data.html#share-of-foreign-students"><i class="fa fa-check"></i><b>6.2.3</b> Share of foreign students</a></li>
<li class="chapter" data-level="6.2.4" data-path="web-data.html"><a href="web-data.html#web-scraping"><i class="fa fa-check"></i><b>6.2.4</b> Web scraping</a></li>
<li class="chapter" data-level="6.2.5" data-path="web-data.html"><a href="web-data.html#most-recent-student-numbers"><i class="fa fa-check"></i><b>6.2.5</b> Most recent student numbers</a></li>
<li class="chapter" data-level="6.2.6" data-path="web-data.html"><a href="web-data.html#the-long-run-trend"><i class="fa fa-check"></i><b>6.2.6</b> The long run trend</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="geo-data.html"><a href="geo-data.html"><i class="fa fa-check"></i><b>7</b> Geo Data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="geo-data.html"><a href="geo-data.html#geo-coordinates"><i class="fa fa-check"></i><b>7.1</b> Geo coordinates</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="geo-data.html"><a href="geo-data.html#where-are-you"><i class="fa fa-check"></i><b>7.1.1</b> Where Are You?</a></li>
<li class="chapter" data-level="7.1.2" data-path="geo-data.html"><a href="geo-data.html#latitude-and-longitude"><i class="fa fa-check"></i><b>7.1.2</b> Latitude and longitude</a></li>
<li class="chapter" data-level="7.1.3" data-path="geo-data.html"><a href="geo-data.html#angles-and-degrees"><i class="fa fa-check"></i><b>7.1.3</b> Angles and Degrees</a></li>
<li class="chapter" data-level="7.1.4" data-path="geo-data.html"><a href="geo-data.html#coordinate-reference-system"><i class="fa fa-check"></i><b>7.1.4</b> Coordinate Reference System</a></li>
<li class="chapter" data-level="7.1.5" data-path="geo-data.html"><a href="geo-data.html#distance-measurement"><i class="fa fa-check"></i><b>7.1.5</b> Distance measurement</a></li>
<li class="chapter" data-level="7.1.6" data-path="geo-data.html"><a href="geo-data.html#points-and-polygons"><i class="fa fa-check"></i><b>7.1.6</b> Points And Polygons</a></li>
<li class="chapter" data-level="7.1.7" data-path="geo-data.html"><a href="geo-data.html#shapefiles"><i class="fa fa-check"></i><b>7.1.7</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="geo-data.html"><a href="geo-data.html#google-takeout"><i class="fa fa-check"></i><b>7.2</b> Google Takeout</a></li>
<li class="chapter" data-level="7.3" data-path="geo-data.html"><a href="geo-data.html#blood-donation"><i class="fa fa-check"></i><b>7.3</b> Blood Donation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>8</b> Missing Data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="missing-data.html"><a href="missing-data.html#types-of-missing-data"><i class="fa fa-check"></i><b>8.1</b> Types of Missing Data</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="missing-data.html"><a href="missing-data.html#missing-completely-at-random-mcar"><i class="fa fa-check"></i><b>8.1.1</b> Missing Completely at Random (MCAR)</a></li>
<li class="chapter" data-level="8.1.2" data-path="missing-data.html"><a href="missing-data.html#missing-at-random-mar"><i class="fa fa-check"></i><b>8.1.2</b> Missing at Random (MAR)</a></li>
<li class="chapter" data-level="8.1.3" data-path="missing-data.html"><a href="missing-data.html#missing-not-at-random-mnar"><i class="fa fa-check"></i><b>8.1.3</b> Missing Not at Random (MNAR)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="missing-data.html"><a href="missing-data.html#causes-of-missing-data"><i class="fa fa-check"></i><b>8.2</b> Causes of Missing Data</a></li>
<li class="chapter" data-level="8.3" data-path="missing-data.html"><a href="missing-data.html#causes-of-missing-data-1"><i class="fa fa-check"></i><b>8.3</b> Causes of Missing Data</a></li>
<li class="chapter" data-level="8.4" data-path="missing-data.html"><a href="missing-data.html#causes-of-missing-data-2"><i class="fa fa-check"></i><b>8.4</b> Causes of Missing Data</a></li>
<li class="chapter" data-level="8.5" data-path="missing-data.html"><a href="missing-data.html#causes-of-missing-data-3"><i class="fa fa-check"></i><b>8.5</b> Causes of Missing Data</a></li>
<li class="chapter" data-level="8.6" data-path="missing-data.html"><a href="missing-data.html#missing-data-in-r"><i class="fa fa-check"></i><b>8.6</b> Missing Data in R</a></li>
</ul></li>
<li class="part"><span><b>III Models</b></span></li>
<li class="chapter" data-level="9" data-path="relationships.html"><a href="relationships.html"><i class="fa fa-check"></i><b>9</b> Relationships</a>
<ul>
<li class="chapter" data-level="9.1" data-path="relationships.html"><a href="relationships.html#storks-deliver-babies"><i class="fa fa-check"></i><b>9.1</b> Storks Deliver Babies</a></li>
<li class="chapter" data-level="9.2" data-path="relationships.html"><a href="relationships.html#statistics"><i class="fa fa-check"></i><b>9.2</b> Statistics</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="relationships.html"><a href="relationships.html#variance"><i class="fa fa-check"></i><b>9.2.1</b> Variance</a></li>
<li class="chapter" data-level="9.2.2" data-path="relationships.html"><a href="relationships.html#standard-deviation"><i class="fa fa-check"></i><b>9.2.2</b> Standard Deviation</a></li>
<li class="chapter" data-level="9.2.3" data-path="relationships.html"><a href="relationships.html#covariance"><i class="fa fa-check"></i><b>9.2.3</b> Covariance</a></li>
<li class="chapter" data-level="9.2.4" data-path="relationships.html"><a href="relationships.html#correlation"><i class="fa fa-check"></i><b>9.2.4</b> Correlation</a></li>
<li class="chapter" data-level="9.2.5" data-path="relationships.html"><a href="relationships.html#an-early-glimpse-into-regression"><i class="fa fa-check"></i><b>9.2.5</b> An Early Glimpse into Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="relationships.html"><a href="relationships.html#visualizations"><i class="fa fa-check"></i><b>9.3</b> Visualizations</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="relationships.html"><a href="relationships.html#storks-and-population-in-a-scatterplot"><i class="fa fa-check"></i><b>9.3.1</b> Storks and Population in a Scatterplot</a></li>
<li class="chapter" data-level="9.3.2" data-path="relationships.html"><a href="relationships.html#storks-and-population-in-a-barplot"><i class="fa fa-check"></i><b>9.3.2</b> Storks and Population in a Barplot</a></li>
<li class="chapter" data-level="9.3.3" data-path="relationships.html"><a href="relationships.html#storks-and-area"><i class="fa fa-check"></i><b>9.3.3</b> Storks and Area</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="relationships.html"><a href="relationships.html#spurious-relationships"><i class="fa fa-check"></i><b>9.4</b> Spurious Relationships</a></li>
<li class="chapter" data-level="" data-path="relationships.html"><a href="relationships.html#readings"><i class="fa fa-check"></i>Readings</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression.html"><a href="regression.html#old-but-gold"><i class="fa fa-check"></i><b>10.1</b> Old but Gold</a></li>
<li class="chapter" data-level="10.2" data-path="regression.html"><a href="regression.html#data-is-everywhere-1"><i class="fa fa-check"></i><b>10.2</b> Data is everywhere</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="regression.html"><a href="regression.html#data-in-a-table"><i class="fa fa-check"></i><b>10.2.1</b> Data in a table</a></li>
<li class="chapter" data-level="10.2.2" data-path="regression.html"><a href="regression.html#data-in-a-graph"><i class="fa fa-check"></i><b>10.2.2</b> Data in a graph</a></li>
<li class="chapter" data-level="10.2.3" data-path="regression.html"><a href="regression.html#the-trend"><i class="fa fa-check"></i><b>10.2.3</b> The trend</a></li>
<li class="chapter" data-level="10.2.4" data-path="regression.html"><a href="regression.html#the-blackbox"><i class="fa fa-check"></i><b>10.2.4</b> The blackbox</a></li>
<li class="chapter" data-level="10.2.5" data-path="regression.html"><a href="regression.html#nobodys-perfect"><i class="fa fa-check"></i><b>10.2.5</b> Nobody's perfect</a></li>
<li class="chapter" data-level="10.2.6" data-path="regression.html"><a href="regression.html#vocab-wrap-up"><i class="fa fa-check"></i><b>10.2.6</b> Vocab Wrap-Up</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="regression.html"><a href="regression.html#for-the-truly-dedicated"><i class="fa fa-check"></i><b>10.3</b> For the truly dedicated</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="regression.html"><a href="regression.html#algebra"><i class="fa fa-check"></i><b>10.3.1</b> Algebra</a></li>
<li class="chapter" data-level="10.3.2" data-path="regression.html"><a href="regression.html#analysis"><i class="fa fa-check"></i><b>10.3.2</b> Analysis</a></li>
<li class="chapter" data-level="10.3.3" data-path="regression.html"><a href="regression.html#take-the-long-way-home"><i class="fa fa-check"></i><b>10.3.3</b> Take the Long Way Home</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="regression.html"><a href="regression.html#survival-of-the-fittest-line"><i class="fa fa-check"></i><b>10.4</b> Survival of the Fittest Line</a></li>
<li class="chapter" data-level="10.5" data-path="regression.html"><a href="regression.html#on-the-shoulders-of-giants"><i class="fa fa-check"></i><b>10.5</b> On the Shoulders of Giants</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>11</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="linear-regression.html"><a href="linear-regression.html#what-you-deserve-is-what-you-get"><i class="fa fa-check"></i><b>11.1</b> What You Deserve Is What You Get</a></li>
<li class="chapter" data-level="11.2" data-path="linear-regression.html"><a href="linear-regression.html#data-sample"><i class="fa fa-check"></i><b>11.2</b> Data &amp; Sample</a></li>
<li class="chapter" data-level="11.3" data-path="linear-regression.html"><a href="linear-regression.html#data-visualization-1"><i class="fa fa-check"></i><b>11.3</b> Data Visualization</a></li>
<li class="chapter" data-level="11.4" data-path="linear-regression.html"><a href="linear-regression.html#simplest-regression"><i class="fa fa-check"></i><b>11.4</b> Simplest Regression</a></li>
<li class="chapter" data-level="11.5" data-path="linear-regression.html"><a href="linear-regression.html#simple-regression"><i class="fa fa-check"></i><b>11.5</b> Simple Regression</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="linear-regression.html"><a href="linear-regression.html#x-is-continuous"><i class="fa fa-check"></i><b>11.5.1</b> X is continuous</a></li>
<li class="chapter" data-level="11.5.2" data-path="linear-regression.html"><a href="linear-regression.html#x-is-a-dummy"><i class="fa fa-check"></i><b>11.5.2</b> X is a dummy</a></li>
<li class="chapter" data-level="11.5.3" data-path="linear-regression.html"><a href="linear-regression.html#x-is-categorical"><i class="fa fa-check"></i><b>11.5.3</b> X is categorical</a></li>
<li class="chapter" data-level="11.5.4" data-path="linear-regression.html"><a href="linear-regression.html#x-is-categorical-is-it"><i class="fa fa-check"></i><b>11.5.4</b> X is categorical, is it?</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="linear-regression.html"><a href="linear-regression.html#parallel-slopes"><i class="fa fa-check"></i><b>11.6</b> Parallel Slopes</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="linear-regression.html"><a href="linear-regression.html#x-is-continuous-dummy"><i class="fa fa-check"></i><b>11.6.1</b> X is continuous + dummy</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="linear-regression.html"><a href="linear-regression.html#model-comparison"><i class="fa fa-check"></i><b>11.7</b> Model Comparison</a></li>
<li class="chapter" data-level="11.8" data-path="linear-regression.html"><a href="linear-regression.html#transform-to-perform"><i class="fa fa-check"></i><b>11.8</b> Transform to Perform</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="interaction-models.html"><a href="interaction-models.html"><i class="fa fa-check"></i><b>12</b> Interaction Models</a>
<ul>
<li class="chapter" data-level="12.1" data-path="interaction-models.html"><a href="interaction-models.html#motivation"><i class="fa fa-check"></i><b>12.1</b> Motivation</a></li>
<li class="chapter" data-level="12.2" data-path="interaction-models.html"><a href="interaction-models.html#data-sample-1"><i class="fa fa-check"></i><b>12.2</b> Data &amp; Sample</a></li>
<li class="chapter" data-level="12.3" data-path="interaction-models.html"><a href="interaction-models.html#throwback-parallel-slopes"><i class="fa fa-check"></i><b>12.3</b> Throwback Parallel Slopes</a></li>
<li class="chapter" data-level="12.4" data-path="interaction-models.html"><a href="interaction-models.html#regression-with-moderators"><i class="fa fa-check"></i><b>12.4</b> Regression with Moderators</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="interaction-models.html"><a href="interaction-models.html#dummy-dummy"><i class="fa fa-check"></i><b>12.4.1</b> Dummy * Dummy</a></li>
<li class="chapter" data-level="12.4.2" data-path="interaction-models.html"><a href="interaction-models.html#categorical-dummy"><i class="fa fa-check"></i><b>12.4.2</b> Categorical * Dummy</a></li>
<li class="chapter" data-level="12.4.3" data-path="interaction-models.html"><a href="interaction-models.html#continuous-dummy"><i class="fa fa-check"></i><b>12.4.3</b> Continuous * Dummy</a></li>
<li class="chapter" data-level="12.4.4" data-path="interaction-models.html"><a href="interaction-models.html#continuous-continuous"><i class="fa fa-check"></i><b>12.4.4</b> Continuous * Continuous</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="interaction-models.html"><a href="interaction-models.html#model-comparison-1"><i class="fa fa-check"></i><b>12.5</b> Model Comparison</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>13</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="logistic-regression.html"><a href="logistic-regression.html#think-inside-the-box"><i class="fa fa-check"></i><b>13.1</b> Think inside the box</a></li>
<li class="chapter" data-level="13.2" data-path="logistic-regression.html"><a href="logistic-regression.html#from-probability-to-odds"><i class="fa fa-check"></i><b>13.2</b> From probability to odds</a></li>
<li class="chapter" data-level="13.3" data-path="logistic-regression.html"><a href="logistic-regression.html#from-odds-to-log-of-odds"><i class="fa fa-check"></i><b>13.3</b> From odds to log of odds</a></li>
<li class="chapter" data-level="13.4" data-path="logistic-regression.html"><a href="logistic-regression.html#titanic-survival"><i class="fa fa-check"></i><b>13.4</b> Titanic Survival</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#the-data"><i class="fa fa-check"></i><b>13.4.1</b> The Data</a></li>
<li class="chapter" data-level="13.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#no-predictor-variables"><i class="fa fa-check"></i><b>13.4.2</b> No Predictor Variables</a></li>
<li class="chapter" data-level="13.4.3" data-path="logistic-regression.html"><a href="logistic-regression.html#single-dichotomous-predictor"><i class="fa fa-check"></i><b>13.4.3</b> Single Dichotomous Predictor</a></li>
<li class="chapter" data-level="13.4.4" data-path="logistic-regression.html"><a href="logistic-regression.html#effect-plot"><i class="fa fa-check"></i><b>13.4.4</b> Effect plot</a></li>
<li class="chapter" data-level="13.4.5" data-path="logistic-regression.html"><a href="logistic-regression.html#chi-square"><i class="fa fa-check"></i><b>13.4.5</b> Chi Square</a></li>
<li class="chapter" data-level="13.4.6" data-path="logistic-regression.html"><a href="logistic-regression.html#some-are-more-equal-than-others"><i class="fa fa-check"></i><b>13.4.6</b> Some Are More Equal Than Others</a></li>
<li class="chapter" data-level="13.4.7" data-path="logistic-regression.html"><a href="logistic-regression.html#the-cheaper-the-deader"><i class="fa fa-check"></i><b>13.4.7</b> The Cheaper The Deader?</a></li>
<li class="chapter" data-level="13.4.8" data-path="logistic-regression.html"><a href="logistic-regression.html#the-bigger-picture"><i class="fa fa-check"></i><b>13.4.8</b> The Bigger Picture</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="marginal-effects.html"><a href="marginal-effects.html"><i class="fa fa-check"></i><b>14</b> Marginal Effects</a>
<ul>
<li class="chapter" data-level="14.0.1" data-path="marginal-effects.html"><a href="marginal-effects.html#marginal-effects-at-representatives"><i class="fa fa-check"></i><b>14.0.1</b> Marginal effects at representatives</a></li>
<li class="chapter" data-level="14.0.2" data-path="marginal-effects.html"><a href="marginal-effects.html#marginal-effects-at-the-mean"><i class="fa fa-check"></i><b>14.0.2</b> Marginal effects at the mean</a></li>
<li class="chapter" data-level="14.0.3" data-path="marginal-effects.html"><a href="marginal-effects.html#average-marginal-effects"><i class="fa fa-check"></i><b>14.0.3</b> Average marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html"><i class="fa fa-check"></i><b>15</b> Software is everywhere</a>
<ul>
<li class="chapter" data-level="15.1" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#software"><i class="fa fa-check"></i><b>15.1</b> Software</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#command-line-interface-cli"><i class="fa fa-check"></i><b>15.1.1</b> Command line interface (CLI)</a></li>
<li class="chapter" data-level="15.1.2" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#graphical-user-interface-gui"><i class="fa fa-check"></i><b>15.1.2</b> Graphical user interface (GUI)</a></li>
<li class="chapter" data-level="15.1.3" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#integrated-development-environment-ide"><i class="fa fa-check"></i><b>15.1.3</b> Integrated development environment (IDE)</a></li>
<li class="chapter" data-level="15.1.4" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#online-compiler"><i class="fa fa-check"></i><b>15.1.4</b> Online Compiler</a></li>
<li class="chapter" data-level="15.1.5" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#cloud-solutions"><i class="fa fa-check"></i><b>15.1.5</b> Cloud solutions</a></li>
<li class="chapter" data-level="15.1.6" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#dashboards"><i class="fa fa-check"></i><b>15.1.6</b> Dashboards</a></li>
<li class="chapter" data-level="15.1.7" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#shiny-apps"><i class="fa fa-check"></i><b>15.1.7</b> Shiny Apps</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#file-formats"><i class="fa fa-check"></i><b>15.2</b> File formats</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#text-files"><i class="fa fa-check"></i><b>15.2.1</b> Text files</a></li>
<li class="chapter" data-level="15.2.2" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#text-with-structure"><i class="fa fa-check"></i><b>15.2.2</b> Text with structure</a></li>
<li class="chapter" data-level="15.2.3" data-path="software-is-everywhere.html"><a href="software-is-everywhere.html#file-formats-1"><i class="fa fa-check"></i><b>15.2.3</b> File formats</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a>
<ul>
<li class="chapter" data-level="15.3" data-path="references.html"><a href="references.html#resources"><i class="fa fa-check"></i><b>15.3</b> Resources</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://marco-kuehne.com/" target="blank">Visit my personal page</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Becoming Fluent in Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<br>
<div class = infobox>
This book is <b>Work in Progress</b>. I appreciate your feedback to make the book better.
</div>
<div id="relationships" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Relationships<a href="relationships.html#relationships" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><small></p>
<blockquote>
<p>“[M]y ally is the Force, and a powerful ally it is. Life creates it, makes it grow. Its energy surrounds us, binds us. Luminous beings are we, not this crude matter. You must feel the Force flow around you. Here, between you, me, the tree, the rock, yes, even between the land and the ship.”</p>
<footer>
Yoda. -- Episode V: The Empire Strikes Back
</footer>
</blockquote>
<blockquote>
<p>"I'm not talking about pagan voodoo here - I'm talking about something REAL and measurable in the biology of the forest. What we think we know is that there's some kind of electrochemical communication between the roots of the trees, like the synapses between neurons. Each tree has ten to the fourth connections to the trees around it, and there are ten to the twelfth trees on Pandora. That's more connections than the human brain. It's a network - a global network. The Na'vi can access it, they can upload and download data - memories - at sites like the one you just destroyed."</p>
<footer>
Dr. Grace Augustine. -- Avatar
</footer>
</blockquote>
<p></small></p>
<p>Welcome to a chapter where we explore the connections that make our social world tick. Think about how Yoda talks about the Force binding everything in the Star Wars galaxy and how Dr. Grace Augustine explains the real, measurable connections in Pandora's forest. Well, social scientists do something similar in our world – we study the relationships that shape our lives.</p>
<p>A relationship is the way in which two or more concepts are connected. Consider these examples: Can money truly bring happiness <span class="citation">(<a href="references.html#ref-easterlin1973does">Easterlin 1973</a>)</span>? Intriguing examples abound, such as exploring the relationship between social media use and sleep quality <span class="citation">(<a href="references.html#ref-alonzo2021interplay">Alonzo et al. 2021</a>)</span>, investigating the impact of attachment styles on adult romantic relationships <span class="citation">(<a href="references.html#ref-feeney1990attachment">Feeney and Noller 1990</a>)</span>, and studying the interplay between gender diversity and team performance <span class="citation">(<a href="references.html#ref-schneid2015influence">Schneid et al. 2015</a>)</span>. Additionally, researchers investigate the connection between parental involvement and academic achievement <span class="citation">(<a href="references.html#ref-wilder2014effects">Wilder 2014</a>)</span>, and scrutinize how perceived crime levels influence quality of life <span class="citation">(<a href="references.html#ref-kitchen2010quality">Kitchen and Williams 2010</a>)</span>. The study conducted by Heim and Heim (2023) further delves into the secrets behind enduring relationships, with younger couples seeking insights on factors like commitment, altruism, shared values, good communication, compromise, love, and persistence from older couples with over 40 years of marriage experience <span class="citation">(<a href="references.html#ref-heim2023did">Heim and Heim 2023</a>)</span>.</p>
<p>In our example, we explore the stork-baby relationship by measuring the number of stork pairs and human population as continuous variables. Using a <em>scatter plot</em>, we depict their connection as dots on a graph. We also try another way by changing one of the continuous things into groups, like putting them in boxes. We then use a <em>barplot</em> to show this connection. This helps us see both the detailed view of the continuous things and the simpler picture when we group them. It gives readers a good understanding of how things are related in different ways.</p>
<!-- A correlation estimate may not represent the relationship best. Beware of spurious relationships, for they can lead us astray in our quest for understanding. Correlation can be the beginning of a more thorough research inquiry.  -->
<!-- <center> -->
<!-- <iframe width="560" height="315" src="https://youtu.be/yObnRvIdDvk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
<!-- </center> -->
<div id="storks-deliver-babies" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Storks Deliver Babies<a href="relationships.html#storks-deliver-babies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Stork_bringing_baby_-_Colmar%2C_Alsace%2C_2016.05.18_%2835%29.jpg/1920px-Stork_bringing_baby_-_Colmar%2C_Alsace%2C_2016.05.18_%2835%29.jpg" alt="Stork bringing baby - Colmar, Alsace." width="60%" />
<p class="caption">
Figure 9.1: Stork bringing baby - Colmar, Alsace.
</p>
</div>
<p>The relationship between the number of storks and the human population is a classic example used to illustrate the concept that correlation does not imply causation <span class="citation">(<a href="references.html#ref-matthews2000storks">Matthews 2000</a>)</span>. It is based on the familiar folk tale that babies are delivered by storks. People noticed a positive correlation between the number of storks in an area or country and the number of human babies born. Stork populations and human populations seem to increase or decrease together.</p>
<p>Although storks are not responsible for delivering babies, a careless interpretation of correlation and p-values can lead to unreliable conclusions.</p>
<div class="reading">
<div class="titelreading">
<h2>
International White Stork Census
</h2>
</div>
<p>The first International White Stork Census was initiated by Prof. Ernst Schüz in 1934 and thus has a long history. Since 1974, it has taken place at ten-yearly intervals. So far, it has been possible to enthuse countless ornithologists and people interested in protecting White Storks to record their numbers at regular intervals.</p>
</div>
<p>Ressource: <a href="https://bergenhusen.nabu.de/imperia/md/nabu/images/nabu/einrichtungen/bergenhusen/zensus_ergebnisse_2004.pdf">Results of the 6th International White Stork Census 2004/2005</a></p>
<p>We have data on stork and human population for 28 countries in 2005.</p>
<div class="datatables html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-2a5b865c1a06a65a4204" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-2a5b865c1a06a65a4204">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"],["Albania","Austria","Belgium","Belarus","Bosnia Herzegowina","Bulgaria","Czech Republic","Denmark","Estonia","France","Germany","Greece","The Netherlands","Hungary","Italy","Latvia","Lithuania","Poland","Portugal","Romania","Russia","Slovenia","Slovakia","Spain","Sweden","Switzerland","Turkey","Ukraine"],[2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005],[3,395,50,21362,40,4826,814,3,4500,975,4482,2157,562,5200,50,10600,13000,52500,7685,5500,10200,240,1331,33217,29,198,6195,30000],["ALB","AUT","BEL","BLR","BIH","BGR","CZE","DNK","EST","FRA","DEU","GRC","NLD","HUN","ITA","LVA","LTU","POL","PRT","ROU","RUS","SVN","SVK","ESP","SWE","CHE","TUR","UKR"],[28748,83870,30528,207600,51129,110910,78866,43094,45226,547030,357021,131940,41526,93030,301230,64589,65200,312685,92391,237500,17075200,20273,48845,504782,449964,41290,780580,603700],[3.09,8.25,10.55,9.56,3.77,7.69,10.26,5.42,1.36,61.12,81.59999999999999,11.22,16.37,10.09,58.28,2.25,3.34,38.37,10.51,21.42,143.67,1.99,5.4,44.02,9.039999999999999,7.39,67.90000000000001,46.89],[1.95,1.38,1.68,1.26,1.32,1.25,1.19,1.76,1.39,1.88,1.35,1.29,1.74,1.3,1.31,1.29,1.28,1.26,1.45,1.29,1.3,1.21,1.22,1.28,1.67,1.41,2.37,1.15],[1.44,4.85,10.27,6.96,1.66,5.42,7.55,4.65,0.93,47.23,62.05,8.41,13.52,6.69,39.84,1.53,2.23,23.57,6.08,11.4,105.51,1.03,3,34.03,7.62,5.44,46.07,31.79]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Country<\/th>\n      <th>Year<\/th>\n      <th>Storks<\/th>\n      <th>code<\/th>\n      <th>Area<\/th>\n      <th>Population<\/th>\n      <th>Fertility<\/th>\n      <th>UrbanPop<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"iDisplayLength":5,"columnDefs":[{"className":"dt-right","targets":[2,3,5,6,7,8]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Country","targets":1},{"name":"Year","targets":2},{"name":"Storks","targets":3},{"name":"code","targets":4},{"name":"Area","targets":5},{"name":"Population","targets":6},{"name":"Fertility","targets":7},{"name":"UrbanPop","targets":8}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p><code>Storks</code> is the number of pairs of storks in that country. The <code>Area</code> is in square kilometers. <code>Population</code> is the total population in million whereas <code>UrbanPop</code> is the population living in urban areas. <code>Fertility</code> refers to the total fertility rate, that is the average number of children that would be born to a female over their lifetime.</p>
<p>The key characteristics of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
NUnique
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Max
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Histogram
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Storks
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
7718.36
</td>
<td style="text-align:right;">
52500.00
</td>
<td style="text-align:right;">
12413.07
</td>
<td style="text-align:right;">
▇▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
Area
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
20273.00
</td>
<td style="text-align:right;">
801740.96
</td>
<td style="text-align:right;">
17075200.00
</td>
<td style="text-align:right;">
3196023.02
</td>
<td style="text-align:right;">
▇
</td>
</tr>
<tr>
<td style="text-align:left;">
Population
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
1.36
</td>
<td style="text-align:right;">
25.03
</td>
<td style="text-align:right;">
143.67
</td>
<td style="text-align:right;">
32.69
</td>
<td style="text-align:right;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
Fertility
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
1.15
</td>
<td style="text-align:right;">
1.44
</td>
<td style="text-align:right;">
2.37
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
▄▇▁▂▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
UrbanPop
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
17.88
</td>
<td style="text-align:right;">
105.51
</td>
<td style="text-align:right;">
24.00
</td>
<td style="text-align:right;">
▇▁▁▁▁
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Haikara_%28White_stork%29_%281%29_Koski_Tl._9.7.2015.jpg/1280px-Haikara_%28White_stork%29_%281%29_Koski_Tl._9.7.2015.jpg" alt="The first known pair in Finland (2015), representing a northward expansion compared to the species' historical breeding range." width="60%" />
<p class="caption">
Figure 9.2: The first known pair in Finland (2015), representing a northward expansion compared to the species' historical breeding range.
</p>
</div>
</div>
<div id="statistics" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Statistics<a href="relationships.html#statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before venturing into specific inquiries, it is essential to establish a solid foundation by introducing key concepts such as <em>variance</em>, <em>covariance</em>, <em>correlation</em>, and <em>levels of measurement</em>. The understanding of variance is paramount as it provides valuable insights into the degree of variability within a variable. Covariance, the measure of how two variables change together, assumes a pivotal role in unveiling the direction of association between them. The standardized measure of association, correlation, plays a central role in quantifying the strength and direction of relationships.</p>
<div id="variance" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Variance<a href="relationships.html#variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The map shows the number of stork pairs for the selected countries.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The range goes from 3 pairs in Albania to 52500 pairs of storks in Poland. There is high variability in the number of storks. The <em>variance</em> is a measure for variability of data.</p>
<div class="defbox">
<div class="titeldefbox">
<h2>
Definition
</h2>
</div>
<p>The <strong><u id='variance'>variance</u></strong> is defined as the <strong>average quadratic deviation from the mean</strong>.</p>
</div>
<p><span class="math display">\[var(x) = \frac{1}{n-1} \sum (x_i - \overline{x} )^2\]</span></p>
<p>To calculate the variance, we subtract each data point <span class="math inline">\(x_i\)</span> from the mean <span class="math inline">\(\overline{x}\)</span>. Then square those deviations and add them up. Finally, there is a scaling factor, we divide by the inverse number of observations minus 1.</p>
<p>The variance of <code>Storks</code> and can be calculated via <code>var()</code> in R. It is 154084389. 150 million of what? The variance is in squared unit, i.e. <em>square storks</em> and thus hard to interpret.</p>
<span class="tippy html-widget html-fill-item-overflow-hidden html-fill-item" height="480" id="htmlwidget-c96e4b1ccde305d08eef" width="672"></span>
<script type="application/json" data-for="htmlwidget-c96e4b1ccde305d08eef">{"x":{"element":"variance","opts":{"content":"The term variance was first introduced by Ronald Fisher in his 1918 paper *The Correlation Between Relatives on the Supposition of Mendelian Inheritance*."}},"evals":[],"jsHooks":[]}</script>
<div class="dedicated">
<div class="titeldedicated">
<h2>
Truly Dedicated
</h2>
</div>
<p>When you collect data from every member of the population that you’re interested in, you can get an exact value for <em>population variance</em>. When you collect data from a sample, the <em>sample variance</em> is used to make estimates or inferences about the population variance. Sample variance is divided by <span class="math inline">\(n-1\)</span>. Population variance is divided by <span class="math inline">\(n\)</span>.</p>
</div>
<!-- The variance of `x` can be calculated from its components in R as a combination of `sum()`, `mean()` and `length()`. -->
<!-- ```{r, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE} -->
<!-- # Variance by hand -->
<!-- sum( (x-mean(x))^2 )/(length(x) - 1)  -->
<!-- ``` -->
</div>
<div id="standard-deviation" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> Standard Deviation<a href="relationships.html#standard-deviation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<!-- https://www.scribbr.com/statistics/variance/ -->
<!-- http://stla.overblog.com/schematizing-the-variance-as-a-moment-of-inertia -->
<!-- https://stats.stackexchange.com/questions/72208/visualising-the-variance -->
<p>The standard deviation is derived from variance and tells, on average, how far each value lies from the mean. Variance and standard deviation both measure the variability of a variable. The standard deviation is the square root of variance.</p>
<p><span class="math display">\[sd(x) = \sqrt{var(x)} = \sqrt{ \frac{\sum (x_i - \overline{x} )^2}{n-1} } \]</span>
In R, the standard deviation is calculated by <code>sd()</code> like <code>sd(storks$Storks)</code> which yields 12413. The mean of storks <code>mean(storks$Storks)</code> is approximately 7718. The one-dimensional variable <code>Storks</code> is visualized as points on the line.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-8-1.png" width="80%" style="display: block; margin: auto;" /></p>
<!-- https://stats.stackexchange.com/questions/311174/what-does-it-mean-when-three-standard-deviations-away-from-the-mean-i-land-ou -->
<div class="dedicated">
<div class="titeldedicated">
<h2>
Truly Dedicated
</h2>
</div>
<p>In statistics, the empirical rule states that</p>
<ul>
<li>68% of the observed data will occur within the first standard deviation,</li>
<li>95% will take place in the second deviation and</li>
<li>99.7% within the third standard deviation</li>
</ul>
<p>of the mean within a normal distribution. See <a href="https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule">68–95–99.7 rule</a></p>
</div>
<p>The following scatterplot shows the number of storks and the population with their respective means as bold red lines.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-9-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Now, that we know how to describe the variation of each of the two variables, we look for a measure that reflects the co-variation of both variables, i.e. how they change in relation to each other. The new grid of means is a good starting point. When most data points fall into lower left and upper right quadrant, we call this a positive relationship.</p>
</div>
<div id="covariance" class="section level3 hasAnchor" number="9.2.3">
<h3><span class="header-section-number">9.2.3</span> Covariance<a href="relationships.html#covariance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<!-- https://evangelinereynolds.netlify.app/post/geometric-covariance/ -->
<!-- https://stats.stackexchange.com/questions/18058/how-would-you-explain-covariance-to-someone-who-understands-only-the-mean -->
<!-- The covariance of `x` can be calculated from its components in R as a combination of `sum()`, `mean()` and `length()`. -->
<!-- # Covariance by hand -->
<!-- (sum((x-mean(x))*(y-mean(y)))) / (length(x)-1) -->
<p>Covariance is a measure of the joint variability of two variables. The main idea of covariance is to classify three types of relationships: positive, negative or no relationship.</p>
<div class="defbox">
<div class="titeldefbox">
<h2>
Definition
</h2>
</div>
<p>The <strong>covariance</strong> between two variables is the <strong>product of the deviations of x and y from their respective means</strong>.</p>
</div>
<p><span class="math display">\[cov(x,y) = \frac{1}{n-1} \sum\limits (x_i - \bar{x})(y_i - \bar{y})\]</span></p>
<p>For each data point, we multiply the differences with the respective mean. Geometrically, this results in several rectangular areas starting at the intersection of means as a new origin. The covariance sums up all these areas. Finally, the covariance is adjusted by the number of observations. When both values are smaller or greater than the mean, the result will be positive.</p>
<p>In R, the covariance is calculated by <code>cov(storks$Storks, storks$Population)</code> and yields 89235. The positive covariance confirms what we saw in the first scatterplot, the positive association between storks and population. Let's try to visualize the calculation procedure of the covariance.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-10-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="challenge">
<div class="titelchallenge">
<h2>
Your Turn
</h2>
</div>
<p>Can you validate the covariance result from <code>cov(x,y)</code> from the sum of squares from the figure?</p>
</div>
<p>Covariance qualifies a relationship as positive or negative, i.e. the direction of the relationship. Covariance is expressed in units that vary with the data. Because the data are not standardized, you cannot use the covariance statistic to assess the strength of a linear relationship (a covariance of 117.5 can be very low for one relationship and 0.23 very high for another relationship).</p>
<p>We need a measure independent of units in a fixed range, the correlation coefficient.</p>
</div>
<div id="correlation" class="section level3 hasAnchor" number="9.2.4">
<h3><span class="header-section-number">9.2.4</span> Correlation<a href="relationships.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To assess the strength of a relationship between two variables a correlation coefficient is commonly used. It brings variation to a standardized scale between -1 to +1.</p>
<div class="defbox">
<div class="titeldefbox">
<h2>
Definition
</h2>
</div>
<p>The <strong>correlation coefficient</strong> is a statistical measure of the strength and direction of the relationship between two variables.</p>
</div>
<p><span class="math display">\[r(x,y) = \frac{\sum\limits (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum\limits (x_i - \bar{x})^2 \sum\limits (y_i - \bar{y})^2}}\]</span></p>
<p>Does the numerator and denominator remind you of something? The formula is made of the components variance and covariance. Thus, the correlation coefficient formula is often expressed in short as:</p>
<p><span class="math display">\[r(x,y,) = \frac{Cov(x,y)}{\sqrt{Var(x) Var(y)}}\]</span></p>
<p><code>cor()</code> is a basic function to calculate the correlation coefficient.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="relationships.html#cb1-1" tabindex="-1"></a><span class="co"># Basic function </span></span>
<span id="cb1-2"><a href="relationships.html#cb1-2" tabindex="-1"></a><span class="fu">cor</span>(x,y)</span></code></pre></div>
<pre><code>## [1] 0.2199176</code></pre>
<p>The correlation coefficients confirms ones more, there is a positive relationship. You will find thresholds for different fields of research that classify the magnitude of the correlation coefficient as <em>weak</em>, <em>moderate</em> and <em>strong</em>. Social science usually accept lower correlation values to be meaningful. One possible classification could be:</p>
<ul>
<li>above 0.4 is strong</li>
<li>between 0.2 and 0.4 is moderate,</li>
<li>and those below 0.2 are considered weak.</li>
</ul>
<p>Thus we may consider the stork-population-relationship as weak to moderate. Keep in mind that these thresholds are not set in stone. Now, let's turn to <code>cor.test()</code>, a more sophisticated version including a hypothesis test.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="relationships.html#cb3-1" tabindex="-1"></a><span class="co"># Advanced function </span></span>
<span id="cb3-2"><a href="relationships.html#cb3-2" tabindex="-1"></a><span class="fu">cor.test</span>(x,y)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 1.1495, df = 26, p-value = 0.2608
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.1668487  0.5480307
## sample estimates:
##       cor 
## 0.2199176</code></pre>
<!-- ## Statistical significance: p<0.05 (or rule of thumb t>2) -->
<!-- ## t value is 5.6757 -->
<!-- ## p value is 0.01084  -->
<p>The correlation test is based on a t-value (t = 1.1495056) and returns a p-value (0.2608121) for statistical significance.</p>
<div class="defbox">
<div class="titeldefbox">
<h2>
Definition
</h2>
</div>
<p>The <strong>p value</strong> is a statistical measure to determine whether the results of a statistical analysis are statistically significant or if they could have occurred due to random chance.</p>
</div>
<p>Small p-values below 0.05 are usually considered to be statistically significant. This is not the case for our stork-population relationship.</p>
<!-- Please look up the exact formula to produce this t- and p-value and code it in R (each 1 pt).  -->
<!-- Hint: For the t-value you can use a combination of `cor()` and `sqrt()`. For the p-value you can use the `pt()`.  -->
<!-- ```{r, echo=TRUE, message=FALSE, warning=FALSE} -->
<!-- ## Calculate t-value for correlation -->
<!-- t <- cor(x,y) * sqrt(3) / sqrt(1-cor(x,y)^2)  -->
<!-- t -->
<!-- ## Calculate p-value for correlation -->
<!-- ## https://stackoverflow.com/questions/46186115/calculating-p-values-for-given-t-value-in-r -->
<!-- ## needs: t, df and pt (Student t cumulative Distribution) -->
<!-- p <- (1 - pt(q = abs(t), df = 3))*2 -->
<!-- p -->
<!-- ``` -->
<!-- https://stats.stackexchange.com/questions/32464/how-does-the-correlation-coefficient-differ-from-regression-slope -->
</div>
<div id="an-early-glimpse-into-regression" class="section level3 hasAnchor" number="9.2.5">
<h3><span class="header-section-number">9.2.5</span> An Early Glimpse into Regression<a href="relationships.html#an-early-glimpse-into-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, let's consolidate our understanding with a minimal example. Consider 5 observations for two variables, <span class="math inline">\(x = (4, 13, 19, 25, 29)\)</span> and <span class="math inline">\(y = (10, 12, 28, 32, 38)\)</span>. To compute the variance for each variable, we follow a simple process: subtract the mean, square the difference, and sum the results. The mean of <span class="math inline">\(x\)</span> is <input class='webex-solveme nospaces' size='2' data-answer='["18"]'/> while the mean of <span class="math inline">\(y\)</span> is <input class='webex-solveme nospaces' size='2' data-answer='["24"]'/>.</p>
<p><span class="math display">\[
\begin{aligned}
\text{var}(x) &amp;= \frac{1}{4} ( (4 - 18)^2 + (13 - 18)^2 + (19 - 18)^2 + (25 - 18)^2 + (29 - 18)^2) \\
\text{var}(x) &amp;= \frac{1}{4} ( (-14)^2 + (-5)^2 + (1)^2 + (7)^2 + (11)^2) \\
\text{var}(x) &amp;= \frac{1}{4} ( 196 + 25 + 1 + 49 + 121) = \frac{1}{4} (196 + 75 + 121) = \frac{1}{4} (392) \\
\text{var}(x) &amp;=  \frac{1}{4} (392) = 98
\end{aligned}
\]</span></p>
<p>We then calculate the covariance of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. Given the variances and the covariance, we can calculate the correlation coefficient of the two variables.</p>
<p>Now, there is another concept for measuring the connection between two variables: The regression coefficient. Don't worry, for the moment you just need to know that there is an interesting connection between the two.</p>
<p><span class="math display">\[\beta_{x \rightarrow y} = r_{x,y} \cdot \frac{\sigma_y}{\sigma_x} \]</span></p>
<p>The correlation coefficient is the same value no matter the order of the variables. It is symmetric, i.e. the correlation between variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is the same as the correlation between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>. However, the regression coefficient is a bit picky. It does care about the order of things. If you swap the roles of the dependent (<span class="math inline">\(y\)</span>) and independent variables (<span class="math inline">\(x\)</span>), the regression coefficient changes. So, it's like having a favorite direction – it matters which way you're looking when interpreting the relationship.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Observation
</th>
<th style="text-align:left;">
x
</th>
<th style="text-align:left;">
y
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{var}(x)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{var}(y)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{cov}(x, y)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(r_{xy}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\beta_{x \rightarrow y}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
1.2
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
1.2
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
1.2
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
25
</td>
<td style="text-align:left;">
32
</td>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
1.2
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
29
</td>
<td style="text-align:left;">
38
</td>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
1.2
</td>
</tr>
</tbody>
</table>
<p>Notably, if the standard deviations (<span class="math inline">\(\sigma\)</span>) of the two variables are equal, the correlation coefficient and the simple regression coefficient coincide. We can achieve this when variables are on the same scale. The most common way of achieving this is through standardization.</p>
<p><strong>Standardization</strong> is a crucial process in statistics that harmonizes variables by centering them around a mean of 0 and scaling them to have a standard deviation of 1. This transformation ensures that variables operate on a uniform scale, facilitating meaningful comparisons. The standardization formula is expressed as:</p>
<p><span class="math display">\[ z = \frac{x - \bar{x}}{\sigma} \]</span></p>
<p>By subtracting each data point from the mean and dividing by the standard deviation, we create a standardized variable that simplifies the interpretation and comparison of different datasets. The same calculation based on scaled data:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Observation
</th>
<th style="text-align:left;">
<span class="math inline">\(z_x\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(z_y\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{var}(z_x)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{var}(z_y)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{cov}(z_x, z_y)\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(r_{z_x z_y}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\beta_{z_x \rightarrow z_y}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
-1.414
</td>
<td style="text-align:left;">
-1.128
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
-0.505
</td>
<td style="text-align:left;">
-0.967
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
0.101
</td>
<td style="text-align:left;">
0.322
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
0.707
</td>
<td style="text-align:left;">
0.645
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.111
</td>
<td style="text-align:left;">
1.128
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
<td style="text-align:left;">
0.956
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="visualizations" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Visualizations<a href="relationships.html#visualizations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="storks-and-population-in-a-scatterplot" class="section level3 hasAnchor" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Storks and Population in a Scatterplot<a href="relationships.html#storks-and-population-in-a-scatterplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <em>scatterplot</em> is a two-dimensional instrument that shows the number of storks on the x-axis and the population on the y-axis. The blue line illustrates the linear trend between the variables. Since its slope is increasing, it suggests a positive connection between storks and population, i.e. countries with more pairs of storks also tend to have a higher population.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The data doesn't cluster in a nice dot cloud but is spread out in both directions. While some countries only have a hand full of storks, others have tens of thousands. Let's explore this in more detail.</p>
</div>
<div id="storks-and-population-in-a-barplot" class="section level3 hasAnchor" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> Storks and Population in a Barplot<a href="relationships.html#storks-and-population-in-a-barplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <em>barplot</em> is a graphical representation of categorical data where individual bars correspond to different categories, and the length of each bar represents the frequency or value associated with that category.</p>
<p>To illustrate the relationship in a barplot, the number of storks is transformed from a continuous variable to a categorical ordered variable. Stork numbers are grouped into four equal parts (quartiles). For each part, the mean number of population is calculated.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In the first quartile are countries with a range of stork numbers between 3 and 198. For all those countries the average population is about 14 million.</p>
</div>
<div id="storks-and-area" class="section level3 hasAnchor" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Storks and Area<a href="relationships.html#storks-and-area" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>we should also consider area when talking about the stork population relationship. since Additionally, considerations of geographical area size reveal potential confounding factors, where larger areas might exhibit both more storks and higher human populations.</p>
<p>Logarithmic transformations are particularly useful for variables that exhibit skewed distributions, large ranges, or multiplicative relationships. Examples include income, where logarithmic transformation can help normalize the data, making it more symmetric. Population growth rates are often better visualized on a log scale due to their multiplicative nature. Stock prices, influenced by exponential growth or decay, benefit from log scales to highlight percentage changes and identify trends.</p>
<p>This compression can be particularly useful when you have extreme values that would otherwise make the visualization challenging.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-18-1.png" width="672" />
### Storks and Urban Population</p>
<p>Examining the stork-baby relationship in light of the share of urban population provides a more nuanced understanding of the observed correlation. The positive link between stork population and human population may be influenced by several factors.</p>
<p>Storks, as wild creatures, are significantly affected by shifts in habitat due to urbanization. This correlation analysis helps unravel the intricate dynamics of how changes in human habitat impact stork habitats.</p>
<p>Urbanization emerges as another influential factor, with urban areas typically hosting fewer storks but higher human populations, potentially confounding the relationship. Moreover, environmental changes, such as deforestation or urban development, may impact both stork habitats and human populations, introducing confounding variables that could mislead interpretations, making it appear as if storks influence human births. This comprehensive exploration highlights the complexity of the stork-baby relationship and the importance of considering multiple factors for a more accurate interpretation.</p>
<p>Integrating information on the share of urban population into the analysis of the stork-baby relationship offers a more nuanced perspective on the observed correlation. The positive link between stork population and the proportion of urban residents may stem from various contributing factors:</p>
<p>Storks, being wild creatures, can be significantly affected by shifts in habitat resulting from urbanization. Evaluating the correlation between the share of urban population and stork populations aids in understanding the impact of changes in human habitat on stork habitats.</p>
<p><img src="Becoming-Fluent-In-Data_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
</div>
<div id="spurious-relationships" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Spurious Relationships<a href="relationships.html#spurious-relationships" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the stork and baby relationship, the observed correlation between stork populations and birth rates could be influenced by <strong>common causes</strong>, such as geographical area and urbanization. Let's delve into these common causes:</p>
<p>Larger geographical areas might exhibit both more storks and higher human populations. This is not necessarily because storks directly influence birth rates, but rather because larger areas can accommodate larger stork populations and, simultaneously, support higher human populations.</p>
<p>Urban areas tend to have fewer storks but higher human populations. Urbanization can alter habitats and make urban areas less conducive to stork populations, while it concentrates human populations in the same regions.</p>
<p>Reading Skill and Shoe Size:
- Variables: Reading skill and shoe size.
- Confounding Variable: Age.
- Correlation Explanation: Age serves as a confounding variable, influencing both reading skill development and physical growth (shoe size).</p>
<p>Ice Cream Sales and Drowning Incidents:
- Variables: Ice cream sales and drowning incidents.
- Confounding Variable: Temperature.
- Correlation Explanation: Temperature is a confounding variable, affecting both ice cream sales and the number of drowning incidents.</p>
<p>Number of TVs per Household and Life Expectancy:
- Variables: Number of TVs per household and life expectancy.
- Confounding Variable: Socioeconomic status.
- Correlation Explanation: Socioeconomic status is a confounding variable, affecting both the number of TVs owned and life expectancy.</p>
</div>
<div id="readings" class="section level2 unnumbered hasAnchor">
<h2>Readings<a href="relationships.html#readings" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Matthews, R. (2000). Storks deliver babies (p= 0.008). Teaching Statistics, 22(2), 36-38.</li>
</ul>
<!-- https://plato.stanford.edu/entries/relations/ -->
<!-- go together flow together -->
<!-- https://www.nabu.de/imperia/md/content/bergenhusen/130618-nabu-weissstorchenzensus.pdf -->
<!-- https://www.nabu.de/news/2005/zensus.html -->
<!-- https://en.wikipedia.org/wiki/White_stork#/media/File:Europe_stork.png -->

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="missing-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Becoming Fluent In Data.pdf", "Becoming Fluent In Data.epub"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": false
},
"toc_depth": 1,
"toc-title": "Table of Contents",
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
