<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Us Against The Rest | Empirical Research (with R)</title>
  <meta name="description" content="This is my first book." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Us Against The Rest | Empirical Research (with R)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is my first book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Us Against The Rest | Empirical Research (with R)" />
  
  <meta name="twitter:description" content="This is my first book." />
  

<meta name="author" content="Marco Kühne" />


<meta name="date" content="2021-08-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="are-you-nuts.html"/>
<link rel="next" href="methods.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.18/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Empirical Research</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Dust and Dark</a></li>
<li class="part"><span><b>I Research</b></span></li>
<li class="chapter" data-level="1" data-path="teach-learn-repeat.html"><a href="teach-learn-repeat.html"><i class="fa fa-check"></i><b>1</b> Teach – Learn – Repeat</a></li>
<li class="chapter" data-level="2" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html"><i class="fa fa-check"></i><b>2</b> A Question You Care About</a>
<ul>
<li class="chapter" data-level="2.1" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#from-zero-to-hero"><i class="fa fa-check"></i><b>2.1</b> From Zero To Hero</a></li>
<li class="chapter" data-level="2.2" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#from-artists-and-economists"><i class="fa fa-check"></i><b>2.2</b> From Artists and Economists</a></li>
<li class="chapter" data-level="2.3" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#data-is-everywhere"><i class="fa fa-check"></i><b>2.3</b> Data is everywhere</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#data-in-a-table"><i class="fa fa-check"></i><b>2.3.1</b> Data in a table</a></li>
<li class="chapter" data-level="2.3.2" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#data-in-a-graph"><i class="fa fa-check"></i><b>2.3.2</b> Data in a graph</a></li>
<li class="chapter" data-level="2.3.3" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#the-trend"><i class="fa fa-check"></i><b>2.3.3</b> The trend</a></li>
<li class="chapter" data-level="2.3.4" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#the-blackbox"><i class="fa fa-check"></i><b>2.3.4</b> The blackbox</a></li>
<li class="chapter" data-level="2.3.5" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#nobodys-perfect"><i class="fa fa-check"></i><b>2.3.5</b> Nobody’s perfect</a></li>
<li class="chapter" data-level="2.3.6" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#vocab-wrap-up"><i class="fa fa-check"></i><b>2.3.6</b> Vocab Wrap-Up</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#for-the-truly-dedicated"><i class="fa fa-check"></i><b>2.4</b> For the truly dedicated</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#algebra"><i class="fa fa-check"></i><b>2.4.1</b> Algebra</a></li>
<li class="chapter" data-level="2.4.2" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#analysis"><i class="fa fa-check"></i><b>2.4.2</b> Analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#take-the-long-way-home"><i class="fa fa-check"></i><b>2.4.3</b> Take the Long Way Home</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#survival-of-the-fittest-line"><i class="fa fa-check"></i><b>2.5</b> Survival of the Fittest Line</a></li>
<li class="chapter" data-level="2.6" data-path="a-question-you-care-about.html"><a href="a-question-you-care-about.html#on-the-shoulders-of-giants"><i class="fa fa-check"></i><b>2.6</b> On the Shoulders of Giants</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-is-everywhere-1.html"><a href="data-is-everywhere-1.html"><i class="fa fa-check"></i><b>3</b> Data is everywhere</a></li>
<li class="part"><span><b>II Data Analysis</b></span></li>
<li class="chapter" data-level="4" data-path="are-you-nuts.html"><a href="are-you-nuts.html"><i class="fa fa-check"></i><b>4</b> Are you nuts</a></li>
<li class="chapter" data-level="5" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html"><i class="fa fa-check"></i><b>5</b> Us Against The Rest</a>
<ul>
<li class="chapter" data-level="5.1" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#understanding-data"><i class="fa fa-check"></i><b>5.1</b> Understanding Data</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#loading-the-data"><i class="fa fa-check"></i><b>5.1.1</b> Loading the Data</a></li>
<li class="chapter" data-level="5.1.2" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#inspect-the-data"><i class="fa fa-check"></i><b>5.1.2</b> Inspect the Data</a></li>
<li class="chapter" data-level="5.1.3" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#summary-statistics"><i class="fa fa-check"></i><b>5.1.3</b> Summary statistics</a></li>
<li class="chapter" data-level="5.1.4" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#missing-data"><i class="fa fa-check"></i><b>5.1.4</b> Missing data</a></li>
<li class="chapter" data-level="5.1.5" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#standardization"><i class="fa fa-check"></i><b>5.1.5</b> Standardization</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#analysis-10-pt"><i class="fa fa-check"></i><b>5.2</b> Analysis (10 pt)</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#subsample-2-pt"><i class="fa fa-check"></i><b>5.2.1</b> Subsample (2 pt)</a></li>
<li class="chapter" data-level="5.2.2" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#mean-per-group-2-pt"><i class="fa fa-check"></i><b>5.2.2</b> Mean per group (2 pt)</a></li>
<li class="chapter" data-level="5.2.3" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#grouped-boxplot-4-pt"><i class="fa fa-check"></i><b>5.2.3</b> Grouped Boxplot (4 pt)</a></li>
<li class="chapter" data-level="5.2.4" data-path="us-against-the-rest.html"><a href="us-against-the-rest.html#yarrr-the-pirates-quiz-2-pt"><i class="fa fa-check"></i><b>5.2.4</b> YaRrr! The Pirate’s Quiz (2 pt)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>6</b> Methods</a></li>
<li class="part"><span><b>III Appendix</b></span></li>
<li class="chapter" data-level="7" data-path="git-and-github.html"><a href="git-and-github.html"><i class="fa fa-check"></i><b>7</b> Git and Github</a>
<ul>
<li class="chapter" data-level="7.1" data-path="git-and-github.html"><a href="git-and-github.html#install-github-and-git"><i class="fa fa-check"></i><b>7.1</b> Install Github and Git</a></li>
<li class="chapter" data-level="7.2" data-path="git-and-github.html"><a href="git-and-github.html#working-with-git"><i class="fa fa-check"></i><b>7.2</b> Working with Git</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="git-and-github.html"><a href="git-and-github.html#git-version"><i class="fa fa-check"></i><b>7.2.1</b> git version</a></li>
<li class="chapter" data-level="7.2.2" data-path="git-and-github.html"><a href="git-and-github.html#git-config"><i class="fa fa-check"></i><b>7.2.2</b> git config</a></li>
<li class="chapter" data-level="7.2.3" data-path="git-and-github.html"><a href="git-and-github.html#git-init"><i class="fa fa-check"></i><b>7.2.3</b> git init</a></li>
<li class="chapter" data-level="7.2.4" data-path="git-and-github.html"><a href="git-and-github.html#git-status-and-diff"><i class="fa fa-check"></i><b>7.2.4</b> git status and diff</a></li>
<li class="chapter" data-level="7.2.5" data-path="git-and-github.html"><a href="git-and-github.html#git-commit"><i class="fa fa-check"></i><b>7.2.5</b> git commit</a></li>
<li class="chapter" data-level="7.2.6" data-path="git-and-github.html"><a href="git-and-github.html#git-add"><i class="fa fa-check"></i><b>7.2.6</b> git add</a></li>
<li class="chapter" data-level="7.2.7" data-path="git-and-github.html"><a href="git-and-github.html#git-remote-add"><i class="fa fa-check"></i><b>7.2.7</b> git remote add</a></li>
<li class="chapter" data-level="7.2.8" data-path="git-and-github.html"><a href="git-and-github.html#git-push"><i class="fa fa-check"></i><b>7.2.8</b> git push</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="git-and-github.html"><a href="git-and-github.html#basic-routines"><i class="fa fa-check"></i><b>7.3</b> Basic Routines</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="git-and-github.html"><a href="git-and-github.html#add-commit-push"><i class="fa fa-check"></i><b>7.3.1</b> Add + Commit + Push</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="git-and-github.html"><a href="git-and-github.html#resources"><i class="fa fa-check"></i><b>7.4</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="slope-fields.html"><a href="slope-fields.html"><i class="fa fa-check"></i><b>8</b> Slope Fields</a>
<ul>
<li class="chapter" data-level="8.1" data-path="slope-fields.html"><a href="slope-fields.html#definition"><i class="fa fa-check"></i><b>8.1</b> Definition</a></li>
<li class="chapter" data-level="8.2" data-path="slope-fields.html"><a href="slope-fields.html#slope-fields-in-r"><i class="fa fa-check"></i><b>8.2</b> Slope Fields in R</a></li>
<li class="chapter" data-level="8.3" data-path="slope-fields.html"><a href="slope-fields.html#understandable-examples"><i class="fa fa-check"></i><b>8.3</b> Understandable Examples</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="slope-fields.html"><a href="slope-fields.html#y-y"><i class="fa fa-check"></i><b>8.3.1</b> y’ = y</a></li>
<li class="chapter" data-level="8.3.2" data-path="slope-fields.html"><a href="slope-fields.html#y--y"><i class="fa fa-check"></i><b>8.3.2</b> y’ = -y</a></li>
<li class="chapter" data-level="8.3.3" data-path="slope-fields.html"><a href="slope-fields.html#y-x2"><i class="fa fa-check"></i><b>8.3.3</b> y’ = x^2</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="slope-fields.html"><a href="slope-fields.html#initial-value-problem"><i class="fa fa-check"></i><b>8.4</b> Initial value problem</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="http://marco-kuehne.com/" target="blank">Visit my personal page</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Empirical Research (with R)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="us-against-the-rest" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Us Against The Rest</h1>
<!-- https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(19)30034-8/fulltext -->
<div class="infobox2 information">
<details>
<summary>
<p><em>In this exercise you learn:</em></p>
</summary>
<ul>
<li>R Basics: Install and load a package. Load a Stata files into R.</li>
<li>Data Manipulation: <code>tidyverse</code> language (glimpse, count, filter, summarise).</li>
<li>Data Visualization: Grouped boxplots, advanced programming pictograms.</li>
<li>How to find information on the web via Google.</li>
</ul>
</details>
</div>
<p>Groups can be compared via numeric figures or graphical instruments.</p>
<!-- https://stackoverflow.com/questions/48522350/create-an-image-filled-chart-in-r-using-ggplot -->
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-20"></span>
<img src="Empirical-Research_files/figure-html/unnamed-chunk-20-1.png" alt="\label{fig:challenge} The proportion of male and female students. Source: [Gender and Origin of Students of Viadrina (22.11.2020)](https://www.europa-uni.de/de/struktur/verwaltung/dezernat_1/statistiken/2020-wintersemester/4_Staatsangehoerigkeiten.pdf) " width="672" />
<p class="caption">
Figure 5.1:  The proportion of male and female students. Source: <a href="https://www.europa-uni.de/de/struktur/verwaltung/dezernat_1/statistiken/2020-wintersemester/4_Staatsangehoerigkeiten.pdf">Gender and Origin of Students of Viadrina (22.11.2020)</a>
</p>
</div>
<p>In 2020 the majority of students at Viadrina was female (59 %). In 2019 men earned 4.44 € more per hour than women in Germany.</p>
<p>Number have different units. Numerical summaries can be the mean, median or mode. A graphical representation can be a boxplot, histogram or density curve. Note that certain calculations and visualizations only make sense for continuous variables (cf. scale of measurements).</p>
<!-- Remember Figure 1 where we easily compared two percentage numbers filled proportionally in pictograms of men and women? How could we possibly do something like that in R? The purpose of this challenge is to train your skills in searching the internet for similar solutions and adapting code for your own needs. -->
<!-- If you google something like ["How to create a grouped boxplot in r"](https://lmgtfy.app/?q=How+to+create+a+grouped+boxplot+in+r) or ["How to create an image filled with percentage in r"](https://lmgtfy.app/?q=How+to+create+an+image+filled+with+percentage+in+r) the chances are extremely high that first, someone else had the same problem and second, **stackoverflow** will be one of the top google hits. SO is a famous question and answer site for professional and enthusiast programmers and statisticians. -->
<!-- Your challenge: -->
<!-- -   Find a gender difference that you are interested in and would like to share. -->
<!-- -   Remember the source. Cite the source in the figure caption. -->
<!-- -   Look up and modify (long and complicated) code, e.g. from stackoverflow. -->
<!-- -   In the given ggplot `theme_void` is used to remove axes and background, the legend is removed by `legend.position = "none"` and labels are annotated manually via `annotate`. -->
<!-- ```{r, echo=FALSE, out.width="70%", fig.cap="\\label{fig:intro} Possible gender difference in working parttime.", fig.align='center'} -->
<!-- knitr::include_graphics("images/parttime.png") -->
<!-- ``` -->
<div id="understanding-data" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Understanding Data</h2>
<div id="loading-the-data" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Loading the Data</h3>
<p>Go to <a href="https://www.diw.de/en/diw_01.c.603154.en/soep_in_the_college_classroom.html" class="uri">https://www.diw.de/en/diw_01.c.603154.en/soep_in_the_college_classroom.html</a> and download the Stata file <code>soep_lebensz_en.dta</code>. Put this file in the same directory as your R script or markdown and load data as follows (no path):</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="us-against-the-rest.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load package </span></span>
<span id="cb16-2"><a href="us-against-the-rest.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code></pre></div>
<pre><code>## Warning: package &#39;haven&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="us-against-the-rest.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb18-2"><a href="us-against-the-rest.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#soep &lt;- read_dta(&quot;soep_lebensz_en.dta&quot;)</span></span>
<span id="cb18-3"><a href="us-against-the-rest.html#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="us-against-the-rest.html#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb18-5"><a href="us-against-the-rest.html#cb18-5" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb18-6"><a href="us-against-the-rest.html#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;https://www.diw.de/documents/dokumentenarchiv/17/diw_01.c.412698.de/soep_lebensz_en.zip&quot;</span>,temp)</span>
<span id="cb18-7"><a href="us-against-the-rest.html#cb18-7" aria-hidden="true" tabindex="-1"></a>soep <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">unz</span>(temp, <span class="st">&quot;soep_lebensz_en.dta&quot;</span>))</span>
<span id="cb18-8"><a href="us-against-the-rest.html#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">unlink</span>(temp)</span></code></pre></div>
<p>If data is somewhere else, you need to specify the exact path (relative or absolute path) to the data. If you use <code>haven</code> (or any other package) for the first time, you have to install (e.g. via a command <code>install.packages("haven")</code>). You can also install and check packages in the right lower panel (cf. “packages”).</p>
</div>
<div id="inspect-the-data" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Inspect the Data</h3>
<p>The SOEP practice dataset consists of a total of 9 original variables and 12,922 measurements. We can see 9 variables as columns with the <code>glimpse()</code> function. The first two variable <em>(id, year) are identifier</em>. The panel data is in <em>long format, i.e. every row is a person-year combination</em>. It covers five time points. The last two variables are standardized versions (satisfaction and health). Actually we have 5 variables to analyze.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="us-against-the-rest.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb19-2"><a href="us-against-the-rest.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(soep)</span></code></pre></div>
<pre><code>## Rows: 12,922
## Columns: 9
## $ id         &lt;dbl&gt; 312, 399, 399, 457, 457, 457, 748, 761, 761, 1044, 1044, 10~
## $ year       &lt;dbl&gt; 2004, 2000, 2001, 2000, 2002, 2004, 2000, 2000, 2001, 2000,~
## $ sex        &lt;dbl+lbl&gt; 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1~
## $ education  &lt;dbl&gt; NA, 12.0, 12.0, 18.0, 18.0, 18.0, 14.0, 16.0, 16.0, 14.0, 1~
## $ no_kids    &lt;dbl&gt; 1, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2,~
## $ health_org &lt;dbl+lbl&gt; 4, 4, 4, 3, 3, 2, 3, 3, 3, 4, 3, 4, 4, 4, 2, 2, 2, 1, 2~
## $ satisf_org &lt;dbl+lbl&gt;  7,  8,  9,  8,  7,  4,  5,  7,  7,  5,  7,  8,  6,  7,~
## $ health_std &lt;dbl&gt; 0.5670103, 0.5670103, 0.5670103, -0.4639175, -0.4639175, -1~
## $ satisf_std &lt;dbl&gt; -0.09090909, 0.47727272, 1.04545450, 0.47727272, -0.0909090~</code></pre>
<p>First, let’s check the consecutive time points. The <code>count()</code> function provides the number of occurrences for values of a variables.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="us-against-the-rest.html#cb21-1" aria-hidden="true" tabindex="-1"></a>soep <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="us-against-the-rest.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##    year     n
##   &lt;dbl&gt; &lt;int&gt;
## 1  2000  3198
## 2  2001  2690
## 3  2002  2485
## 4  2003  2299
## 5  2004  2250</code></pre>
<p>We observe a decline in observations over time. People drop out of the survey for various reasons (<strong>panel attrition</strong>). SOEP regularly adds refreshment samples to compensate for this. Sometimes we miss data in between years. Person number 457 participated in 2000, 2002 and 2004:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="us-against-the-rest.html#cb23-1" aria-hidden="true" tabindex="-1"></a>soep <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="us-against-the-rest.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(id <span class="sc">==</span> <span class="dv">457</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 9
##      id  year       sex education no_kids       health_org satisf_org health_std
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;      &lt;dbl&gt;
## 1   457  2000  0 [male]        18       0 3 [satisfactory] 8 [8 Sati~     -0.464
## 2   457  2002  0 [male]        18       0 3 [satisfactory] 7 [7 Sati~     -0.464
## 3   457  2004  0 [male]        18       0 2 [poor]         4 [4 Sati~     -1.49 
## # ... with 1 more variable: satisf_std &lt;dbl&gt;</code></pre>
<p>Person 457 was not available in the year 2001 for some reason.</p>
</div>
<div id="summary-statistics" class="section level3" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Summary statistics</h3>
<p>Now let’s have a look at <strong>summary statistics</strong> for the dataset. The <code>stargazer</code> package (with <code>type="text"</code>) displays number of observations, mean, standard deviation, min, max and percentiles to the console or markdown file (it produces a .tex table by default). <code>stargazer</code> requires a dataframe as input. <code>haven</code> created a tibble from the Stata .dta file. Finally, we select all variables but the first two, since they are identifier and any calculation, e.g. the mean of personal IDs, does not make much sense here.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="us-against-the-rest.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb25-2"><a href="us-against-the-rest.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(<span class="fu">as.data.frame</span>(soep)[,(<span class="dv">3</span><span class="sc">:</span><span class="dv">9</span>)], <span class="at">type=</span><span class="st">&quot;text&quot;</span>)</span></code></pre></div>
<pre><code>## 
## =================================================================
## Statistic    N     Mean  St. Dev.  Min   Pctl(25) Pctl(75)  Max  
## -----------------------------------------------------------------
## sex        12,922 0.539   0.499     0       0        1       1   
## education  11,454 11.874  2.469   7.000   10.500   13.000  18.000
## no_kids    12,016 0.647   0.931   0.000   0.000    1.000   3.000 
## health_org 12,907 3.455   0.973   1.000   3.000    4.000   5.000 
## satisf_org 12,922 7.156   1.762     0       6        8       10  
## health_std 12,907 0.005   1.003   -2.526  -0.464   0.567   1.598 
## satisf_std 12,922 -0.002  1.001   -4.068  -0.659   0.477   1.614 
## -----------------------------------------------------------------</code></pre>
<p>The mean of <code>sex</code> is 0.539. What does it tell you?</p>
</div>
<div id="missing-data" class="section level3" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> Missing data</h3>
<p>Check out the first <code>glimpse()</code> table. Have you noticed the value <code>NA</code> in <code>education</code>? <strong>NA</strong> stand for non available and is the indicator for <strong>missing data in R</strong>. We ask for a table count of all values in the data that are either missing or not missing.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="us-against-the-rest.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">is.na</span>(soep))</span></code></pre></div>
<pre><code>## 
##  FALSE   TRUE 
## 113894   2404</code></pre>
<p>One option is substituting values (e.g. the mean) for missing cells (<strong>imputation</strong>). The alternative, for simplicitiy, is removing all rows which contain a missing value in any column. This is called a <strong>complete case analysis</strong>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="us-against-the-rest.html#cb29-1" aria-hidden="true" tabindex="-1"></a>soep_no_na <span class="ot">&lt;-</span> soep <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.))</span></code></pre></div>
</div>
<div id="standardization" class="section level3" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> Standardization</h3>
<p>Look again at the <code>glimpse()</code> output or <code>stargazer()</code> table. Notice two versions of satisfaction and health, i.e. <code>satisf_org</code> and <code>satisf_std</code> which represent satisfaction on the original scale (from 0 to 10) and a <em>standardized</em> version of satisfaction. Health is ranging from 1 to 5. How can we compare the mean of satisfaction and health?</p>
<p>In statistics, <strong>standardization</strong> is the process of putting different variables on the same scale. This process allows you to compare scores between different types of variables (compare apples with apples instead of apples with bananas). Typically, to standardize variables, you calculate the mean and standard deviation for a variable (cf. z-score). Then, for each observed value of the variable, you subtract the mean and divide by the standard deviation.</p>
<p>Consequently, standardized variables have a mean of 0 and a standard deviation of 1.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="us-against-the-rest.html#cb30-1" aria-hidden="true" tabindex="-1"></a>soep_no_na <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="us-against-the-rest.html#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(satisf_std, health_std), <span class="fu">list</span>(mean, sd))) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="us-against-the-rest.html#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">colnames&lt;-</span><span class="st">`</span>(<span class="fu">c</span>(<span class="st">&quot;mean of std. satis&quot;</span>, <span class="st">&quot;sd of std. satis&quot;</span>, </span>
<span id="cb30-4"><a href="us-against-the-rest.html#cb30-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;mean of std. health&quot;</span>, <span class="st">&quot;sd of std. health&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   `mean of std. satis` `sd of std. satis` `mean of std. health` `sd of std. hea~
##                  &lt;dbl&gt;              &lt;dbl&gt;                 &lt;dbl&gt;            &lt;dbl&gt;
## 1              0.00174               1.00               -0.0102            0.998</code></pre>
<p>Here <code>summarise</code> is asked to apply the <code>mean()</code> and <code>sd()</code> function “across” the two columns <code>satisf_std</code> and <code>health_std</code>. The means are close to zero and the standard deviation is close to one. The minor differences result from our complete case analysis (we already dropped some cases which might have been used for the initial standardization).</p>
<!-- Now let's quickly redo this kind of standardization. There are built-in functions such as `scale()`, this should produce a more accurate mean and standard deviation.  -->
<!-- # ```{r} -->
<!-- # mean(scale(soep_no_na$satisf_std)) -->
<!-- # sd(scale(soep_no_na$satisf_std)) -->
<!-- # ``` -->
<!-- Let's do it by hand.  -->
<!-- ```{r} -->
<!-- soep_no_na %>% -->
<!--   mutate(satisf_std_2 = (satisf_org - mean(satisf_org))/sd(satisf_org), -->
<!--          health_std_2 = (health_org - mean(health_org))/sd(health_org)) %>% -->
<!--   dplyr::select(satisf_std, satisf_std_2, health_std, health_std_2) %>% -->
<!--   head(n=5) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- soep_no_na %>% -->
<!--   ggplot(aes(x=satisf_std, color=health_std, fill=health_std)) +  -->
<!--   geom_density() -->
<!-- df <- gather(soep_no_na, key = 'Std_Variable', value = 'Value', contains('std')) -->
<!-- ggplot(df, aes(x = Value, group = Std_Variable, fill = Std_Variable, color = Std_Variable)) +  -->
<!--   geom_density(alpha = 0.3) -->
<!-- ``` -->
</div>
</div>
<div id="analysis-10-pt" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Analysis (10 pt)</h2>
<p>Now, it’s your turn to find and implement R code in order to achieve the following tasks.</p>
<div id="subsample-2-pt" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Subsample (2 pt)</h3>
<p>Create a subsample of people with no children in the household (subsetting). This should be <span class="math inline">\(n=7428\)</span> observations. Call it <code>nokids</code>.</p>
<pre class="r">
  <code class = "hlsj"> <span class="hljs-string"> <br> <br> </span> </code>
  </pre>
</div>
<div id="mean-per-group-2-pt" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Mean per group (2 pt)</h3>
<p>Please calculate the mean of education for men and women and store the means into one or two objects (dependent on how you calculate it). You may use base R or tidyverse functions.</p>
<pre class="r">
  <code class = "hlsj"> <span class="hljs-string"> <br> <br> </span> </code>
  </pre>
</div>
<div id="grouped-boxplot-4-pt" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Grouped Boxplot (4 pt)</h3>
<p>Create a boxplot of years of education grouped by gender (fe/male). A <strong>boxplot</strong> is a method for graphically depicting groups of numerical data through their quartiles. It shows 50 % of the data in a box and the median in the middle of the box and whiskers outsider of the box.</p>
<pre class="r">
  <code class = "hlsj"> <span class="hljs-string"> <br> <br> </span> </code>
  </pre>
<p>Replicate the following figure. You can either do this with base R or <code>ggplot</code>. The labels (title, subtitle, axis) should be identical. Furthermore, add the mean of the groups to the boxplot (as red bold point or something similar).</p>
<p><img src="Empirical-Research_files/figure-html/unnamed-chunk-35-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>The two boxplots look very similar. In both groups the mean is higher than the median. This is an indication that the distribution of education is <strong>skewed</strong> to the right.</p>
<p>Is <code>education</code> a continuous variable? Not really. Actually, students usually graduate after 10 or 12 years of education in Germany.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="us-against-the-rest.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(soep_no_na<span class="sc">$</span>education)</span></code></pre></div>
<pre><code>## 
##    7  8.5    9   10 10.5   11 11.5   12   13   14   15   16   18 
##  175   48  994  339 2822  724 1918  988  556  509  394  327  865</code></pre>
</div>
<div id="yarrr-the-pirates-quiz-2-pt" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> YaRrr! The Pirate’s Quiz (2 pt)</h3>
<p>In chapter <a href="https://bookdown.org/ndphillips/YaRrr/workspace-management-functions.html">9.1. workspace management functions</a> of the bookdown (yeah, that’s right, you can create entire books from inside RStudio!) “YaRrr! The Pirate’s Guide to R” you find a picture of pirate.</p>
<details>
<summary>
<p><em>Danger? I look on the wild side. I laugh in the face of danger! Show me the PiRate!</em></p>
</summary>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-37"></span>
<img src="images/pirate.jpg" alt="\label{fig:pirate}Figure 2: Who's that boy?" width="40%" />
<p class="caption">
Figure 5.2: Figure 2: Who’s that boy?
</p>
</div>
</details>
<p><br></p>
<p>He’s not a random, no-name person. On the contrary, he has a wikipedia article in several languages. Who is he?</p>
<pre class="r">
  <code class = "hlsj"> <span class="hljs-string"> <br> <br> </span> </code>
  </pre>
<!-- ### Grouped Density (2 pt) -->
<!-- A density plot is a representation of the distribution of a numeric variable. It uses a kernel density estimate to show the probability density function of the variable. Please create a density plot of the distribution of education grouped by males and females. -->
<!-- ```{r,  results='asis', echo=F} -->
<!-- cat( -->
<!--   '<pre class="r"> -->
<!--   <code class = "hlsj"> <span class="hljs-string"> <br> <br> </span> </code> -->
<!--   </pre> -->
<!--   ') -->
<!-- ``` -->
<!-- ```{r echo = FALSE, message=FALSE, warning=FALSE, eval=TRUE} -->
<!-- # Change density plot line colors by groups -->
<!-- ggplot(soep_no_na, aes(x=education, color=as.factor(sex))) + -->
<!--   geom_density() + -->
<!--     labs(title = "Density plot of education",  -->
<!--        subtitle = "Subsample of People with no child in household",  -->
<!--        y = "Density", x="Years of education") + -->
<!--   scale_color_discrete(name = "Female") -->
<!--   #geom_vline(data=soep_no_na, aes(xintercept=grp.mean, color=sex2), -->
<!--    #          linetype="dashed") -->
<!-- ``` -->
<!-- ### Group Means (t-test) (4 pt) -->
<!-- https://statsandr.com/blog/student-s-t-test-in-r-and-by-hand-how-to-compare-two-groups-under-different-scenarios/#how-to-compute-students-t-test-by-hand -->
<!-- **Student’s t-test** or t-test (the real name is W.S. Gossett who hid his name due to his position as a worker in a brewery company) is a simple yet very useful statistical test.  -->
<!-- ```{r echo = TRUE} -->
<!-- t.test(education ~ sex, data=soep_no_na) -->
<!-- ``` -->
<!-- Look at the output of the t-test: -->
<!-- - The so called t-statistic is 4.1521 -->
<!-- - The degrees of freedom are 10139 -->
<!-- - The p-value of 3.321e-05 (scientific notation) -->
<!-- - The 95% confidence interval is [0.1057920;0.2950069] -->
<!-- ### Panel data -->
<!-- It is easy to get a cross-section by filtering for a given year. We can be sure that every individual (id) is only included once. But perhaps someone is was not asked or was not part of the survey in this year, but in several other so called waves. Why don't we use his or her data as well? Let's use exactly one observation per person, irrespective of the year.  -->
<!-- **Between** and **Within** Variation.  -->
<!-- First, let's investigate if education is never changing  -->
<!-- ```{r echo = FALSE, eval=TRUE, warning=FALSE, message=FALSE, fig.align = 'center'} -->
<!-- soep_no_na %>% -->
<!--   filter(year == 2000) -->
<!-- library(rlang) -->
<!-- library(dplyr) -->
<!-- XTSUM <- function(data, varname, unit) { -->
<!--   varname <- enquo(varname) -->
<!--   loc.unit <- enquo(unit) -->
<!-- ores <- data %>% summarise(ovr.mean=mean(!! varname, na.rm=TRUE), ovr.sd=sd(!! varname, na.rm=TRUE), ovr.min = min(!! varname, na.rm=TRUE), ovr.max=max(!! varname, na.rm=TRUE), ovr.N=sum(as.numeric((!is.na(!! varname))))) -->
<!-- bmeans <- data %>% group_by(!! loc.unit) %>% summarise(meanx=mean(!! varname, na.rm=T), t.count=sum(as.numeric(!is.na(!! varname)))) -->
<!-- bres <- bmeans %>% ungroup() %>% summarise(between.sd = sd(meanx, na.rm=TRUE), between.min = min(meanx, na.rm=TRUE), between.max=max(meanx, na.rm=TRUE), Units=sum(as.numeric(!is.na(t.count))), t.bar=mean(t.count, na.rm=TRUE)) -->
<!-- wdat <- data %>% group_by(!! loc.unit) %>% mutate(W.x = scale(!! varname, scale=FALSE)) -->
<!-- wres <- wdat %>% ungroup() %>% summarise(within.sd=sd(W.x, na.rm=TRUE), within.min=min(W.x, na.rm=TRUE), within.max=max(W.x, na.rm=TRUE)) -->
<!-- return(list(ores=ores,bres=bres,wres=wres)) -->
<!-- } -->
<!-- XTSUM(soep_no_na, varname=education, unit=id) -->
<!-- ``` -->
<!-- How can we find examples of education change in the data? -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="are-you-nuts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="methods.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Empirical Research.pdf", "Empirical Research.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
